### ISSUE TITLE
chaincode does not seem to recognize failed build

### ISSUE THREAD

**Issue by joequant** [hyperledger-archives/fabric#1046]
This is in reference to the issue #1045 

It appears that when chaincode does not build that the id is cached so that the peer will then refuse to attempt a build if there is another deployment

**Comment by muralisrini** [comment]
@joequant : when you attempt the recreate for #1045 and get the logs as requested, could you also get logs for this issue ?

Will note that the "caching" of image id you mention is likely that docker will not rebuild the image when there is no need to (given that the image itself was built successfully....the problem was only starting the container). You can another image is to re-deploy by changing one of { the chaincode path, the chaincode function/args, the chaincode itself }. Likely in future we will have way to "remove" chaincode and (possibly) "update" existing one.

**Comment by muralisrini** [comment]
@joequant : given #1045 is closed, should this be as well ?

**Comment by joequant** [comment]
Not sure.  #1045 was generating spurtious build errors, but there may be bad caching.
Will close this for now, until we get a better use case of the problem.
