### ISSUE TITLE
Investigate blocking network operations in fabric

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#1056]
Per a discussion with @chetmurthy we should audit the fabric code to ensure that we never expect network operations to only succeed/fail immediately, but instead ensure that we also handle the timeout case.

This can happen when a network host ungracefully loses network connectivity (unplugged ethernet cable) or when TCP behavior degrades to its timeout mechanisms (for instance failed connections might not be rejected with a TCP RST packet, perhaps due to a firewall).

When this behavior is observed, operations which normally do not appear to be blocking (sends, opens, and receives) can block for long periods of time.  If this blocking occurs on a thread/goroutine which has other work to be performed, the single network failure can cause a total network stall.  The code should be audited to ensure this does not happen.

Preliminary investigation shows that the fabric code is most likely not vulnerable to the more insidious half of these errors, as reads are done via a dedicated goroutine per connection.  Documentation in `openchain.proto` says

```
// Accepts a stream of OpenchainMessage during chat session, while receiving
// other OpenchainMessage (e.g. from other peers).
```

This seems to be in parity with the gRPC doc which indicates that:

```
Serve accepts incoming connections on the listener lis, creating a new
ServerTransport and service goroutine for each. The service goroutines
read gRPC requests and then call the registered handlers to reply to 
them. Service returns when lis.Accept fails. 
```

On the sending side, the possibility of a bug of this type seems more likely.  The generated code creates a `Peer_ChatServer` which has a `Send` method which is a wrapper around `ServerStream.SendMsg`, which is documented as:

```
    // SendMsg blocks until it sends m, the stream is done or the stream
    // breaks.
    // On error, it aborts the stream and returns an RPC status on client
    // side. On server side, it simply returns the error to the caller.
    // SendMsg is called by generated code. Also Users can call SendMsg
    // directly when it is really needed in their use cases.
```

Since our broadcast serially invokes `Send` across our peers in a for loop, it seems possible a non-closed TCP state could end up causing the send to block until a timeout occurs.

This is purely preliminary doc research, we should verify this behavior on both the send and receive sides.

**Comment by bmandler** [comment]
On behalf of Yacov Manevich:

I think the issue can be approached by either:
1. Spawning a new goroutine for each peer and sending the message with the goroutine
2. Maintaining a pool of goroutines and a shared channel; putting the message and the recipient into the channel; have the goroutines read from it and send the messages

Any thoughts?

**Comment by jyellick** [comment]
@bmandler My preference would lean toward a go routine per connection (option 1).  I think we will have much more trouble scaling the number of connections than the number of goroutines, and for byzantine fault tolerance, we would need at a very minimum f+1 threads in the pool.

**Comment by corecode** [comment]
The nice thing about blocking sends is that it automatically throttles our own send rate.

Of course, we cannot use blocking sends for all replicas, or byzantine replicas could just prevent progress.  I believe this is what the situation is at the moment.

We may have to move `.Broadcast` into pbft, and only expose `.Unicast` from the stack, so that the consensus plugin can choose its own policy on how to handle unresponsive peers.  For PBFT, it is 2f+1, for some gossip algorithm it may be entirely different.

**Comment by yacovm** [comment]
According to what I measured, sends that come from membership and chaincode **invocations** are non blocking because they are very small and the grpc/stream.go:SendMsg writes the message into the socket and that's it. It doesn't ensure that it was successfully sent to the remote host, it simply transfers the bytes to the lower layers.

I tracked it when I did the parallel Bcast PR and did experiments and measured the amount of time it takes to invoke the Flush method (it was less than 1 micro-second, but there were multiple flushes).
Then I added sleep of 1 ms to the FlushWrite method of http_util.go (in grpc/transport) and then the broadcast time measured was significantly increased. 
Without the modification above, broadcast took a few hundred micro-seconds for a network that had an artificial delay of a few ms.

So I think if the TCP buffers are big enough, and the payload isn't very large (less than a few KBs) - the sending will be non-blocking for most messages except chaincode deployments, which have fat payloads. 

I've observed this behavior in some tests I've been running (this is from the logs):

Deployment with 1 ms delay:
Sending 136169586 bytes to 172.17.0.5:30303 took **1.264016544s**
In contrast: 
 Sending message to stream of type: CONSENSUS 
Sending 108 bytes to 172.17.0.4:30303 took **174.009µs**

**Comment by corecode** [comment]
I set out to implement a timeout on sends, which would address this issue.  However, I cannot find a way to cancel a GRPC stream, both on client as well as server side.  There doesn't seem to be a unified way to do so.

@jeffgarratt

**Comment by jeffgarratt** [comment]
@corecode @jyellick will take a look and see the way we can allow either side to cancel (close) the stream.

**Comment by corecode** [comment]
thanks!
