### ISSUE TITLE
Failing to setup a new docker image

### ISSUE THREAD

**Issue by roy2006** [hyperledger-archives/fabric#1097]
I'm following the instructions given in the [documentation](https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/devnet-setup.md), but getting an error message when I try to create a new docker image (my first).  

Any idea what I'm doing wrong? 

```
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric/core/container$ go test -run BuildImage_Peer
2016/04/14 13:01:27 Log level not recognized '', defaulting to ERROR: logger: invalid log level
2016/04/14 13:01:27 setting Number of procs to 2, was 2
2016/04/14 13:01:27 Creating VM with endpoint: unix:///var/run/docker.sock
2016/04/14 13:01:27 rootDirectory = /opt/gopath/src
2016/04/14 13:01:47 Failed Peer docker build:
Step 1 : FROM openblockchain/baseimage:latest
Pulling repository docker.io/openblockchain/baseimage

--- FAIL: TestVM_BuildImage_Peer (19.79s)
    vm_test.go:76: Error building Peer container: Tag latest not found in repository docker.io/openblockchain/baseimage

FAIL
exit status 1
FAIL    github.com/hyperledger/fabric/core/container    19.840s
```

**Comment by srderson** [comment]
I think you need to exit vagrant and run `vagrant destory` and `vagrant up` again. This should pull down `openblockchain/baseimage` and tag it as latest.

If you've already done that recently, could you post the output from running `docker images` in your vagrant environment?

**Comment by j4n05** [comment]
Hello,

I have the same issue. I have just destroyed and recreated the guest machine as you advised, but the issue still holds. Currently there are no docker images on my vagrant environment (I have removed all old images according to the setting up docs).

I thought that this might be the result of project renaming, as it looks for latest in a repository named openblockchain and not hyperledger. Well, I am not an expert on docker, so maybe I missed something, but manually altering the docker files have not helped. (Although I am not even sure if the repos were renamed.)

Any idea what am I doing wrong?

**Comment by roy2006** [comment]
I followed srderson's advice (`vagrant destory` and then `vagrant up`), and it did the trick.

**Comment by j4n05** [comment]
I did once again (`vagrant destroy` and `vagrant up`) to make sure, but still the same error.

**Comment by srderson** [comment]
@j4n05 Are there any errors running `vagrant up`? The docker image is still called openblockchain because we are working on getting control of the hyperledger org in DockerHub

**Comment by j4n05** [comment]
@srderson I have checked the vagrant log but I haven't seem anything. I mean there are a bunch of warnings but nothing suspicious. Hopefully one of my colleagues with experience in vagrant will have time to help soon. I'll post here if we find something.

**Comment by ryokawajp** [comment]
Hi. I saw the same error when I deploy and query a chaincode, and also in the unit test (Step 3 of the following URL).
[link](https://github.com/hyperledger/fabric#building-the-fabric-core-)

The error messages are as follows:
In the case of querying CC:
`11:36:22.745 [container] build -> ERRO 042 Error building Peer container: Tag latest not found in repository docker.io/openblockchain/baseimage`

In the case of running a unit test:

```
--- FAIL: TestVM_BuildImage_Obcca (4.05s)
        vm_test.go:89: Error building membersrvc container: Tag latest not found in repository docker.io/openblockchain/baseimage

```

I cloned the latest hyperledger fabric code from GitHub today. I am not using Vagrant. Instead, I followed the instruction in the document.
[link](https://github.com/hyperledger/fabric#building-outside-of-vagrant-)

I suppose that there is no docker image with the latest tag in docker repository.
[link](https://hub.docker.com/r/openblockchain/baseimage/)
So I tried using 0.0.9 image instead of the latest by modifying Dockerfile entries in core.yaml, but it did not work. It caused another error at deployment of a chaincode.

`12:34:58.089 [container] build -> ERRO 033 Error building Peer container: The command '/bin/sh -c go install github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example01 && cp src/github.com/hyperledger/fabric/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example01 $GOPATH/bin/e335dfe0c176c5226478a42acbf9c3955ab0eccf8ab68749a5914a83a4ccd7f9ec8f93db0f11acb128f8ff378db384f7fa6cf484d4fbf17d3ab0020087ec5b37' returned a non-zero code: 127
`
Any workaround or comments are welcome.

**Comment by tuand27613** [comment]
This was discussed on the Hyperledger #fabric Slack channel.

See the thread starting at https://hyperledgerproject.slack.com/archives/fabric/p1461116645000096

**Comment by ryokawajp** [comment]
@tuand27613 Thank you.
According to the slack log, I needed to execute:
`$GOPATH/src/github.com/hyperledger/fabric/scripts/provision/docker.sh 0.0.9`
I did this command before launching a peer and it worked fine with the default core.yaml.
This means that we do not need the image with the latest tag, but 0.0.9 tag is fine.
This step is automatically executed when one installs Hyperledger on a Vagrant environment through the execution of fabric/devnet/setup.sh.

**Comment by j4n05** [comment]
Thanks for the advice. I have executed this script:
`$GOPATH/src/github.com/hyperledger/fabric/scripts/provision/docker.sh 0.0.9`
After that I was able to execute `go test -run BuildImage_Peer` without error and the docker images are now created. I am using Vagrant environment and I did everything as written in the documentation.

**Comment by christo4ferris** [comment]
closing this as it seems resolved. please reopen if you disagree
