### ISSUE TITLE
how to install docker image with Building outside of Vagrant?

### ISSUE THREAD

**Issue by zhuang-weiming** [hyperledger-archives/fabric#1123]
I want to build fabric on my Macbook, and run chaincode, web appllication with fabric together.
I am following guide [Building outside of Vagrant](https://github.com/hyperledger/fabric#building-outside-of-vagrant-)

could you kindly tell me what is the detail step about "Docker daemon initialization"?

_Make sure that the Docker daemon initialization includes the options
-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock
Be aware that the Docker bridge (the CORE_VM_ENDPOINT) may not come up at the IP address currently assumed by the test environment (172.17.0.1). Use ifconfig or ip addr to find the docker bridge._

**Comment by bcbrock** [comment]
@WillZhuang  If you want to run outside of the Vagrant environment, you need to install Docker and Docker-compose. The Docker daemon needs to be configured as indicated. 

Look at hyperledger/fabric/devenv/setup.sh to see how it is done inside the Vagrant (Ubuntu) environment and modify as appropriate for your Mac environment. 

I've never tried installing directly on a Mac so that's the most detail I am able to give you. However I will say that the Vagrant environment works very well on a Mac, so it may be easiest to stick with Vagrant. You know you can configure Vagrant networking in a variety of ways, so applications running in the Vagrant environment can easily be set up to communicate with applications running natively on the Mac and in the world at large.

**Comment by zhuang-weiming** [comment]
@bcbrock Thank you for you quick response.
