### ISSUE TITLE
Fix ChaincodeDeploymentSpec and ChaincodeInvocationSpec API

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#1183]
The ChaincodeDeploymentSpec and ChaincodeInvocationSpec API as defined in chaincode.proto needs to be reworked. The main issue is that `ChaincodeDeploymentSpec` and `ChaincodeInvocationSpec` both share `ChaincodeSpec` which results in unnecessary fields when when either deploying or invoking a chaincode. Also, some fields such as `ctorMsg` need to be renamed so that they are more clear.

I will post a proposal soon.

**Comment by ghaskins** [comment]
Just a note to capture that chaincodeType is superfluous in Invoke/Query operations, so ideally cleaned up as part of this effort.

**Comment by adecaro** [comment]
Actually, the chaincode type needs to be at the transaction level in order for the crypto layer to work properly.

**Comment by ghaskins** [comment]
@adecaro this isn't obvious to me why this would be.  Could you elaborate?

**Comment by srderson** [comment]
not clear to me either. Seems we should be able to lookup this information from the DB on an invoke/query if it is needed.

**Comment by adecaro** [comment]
@ghaskins @srderson Actually, deploy/execute/query transactions are encrypted in different ways because they contain different information. Then, once the crypto layer has to pre-validate and then pre-exececute a transaction at the validator side, having the transaction type field allows the crypto layer to know quickly how to decrypt the transaction. Without that field, the crypto layer should try all the possible ways to decrypt a transaction to find out which type the transaction is. This is quite inefficient!

Notice that, the type of a transaction cannot be hidden because the size of a transaction leaks this kind of information. So, for efficiency reason I would prefer to have that field there. If you decide anyway to remove that field then the crypto layer needs to be updates as I said above.

**Comment by ghaskins** [comment]
@adecaro ok, we might be talking about different fields.  chaincodeType is what specifies the type of language the chaincode is implemented with (today only "GOLANG" is supported).  It really has no meaning for anything except deploy, as we invoke/query all chaincode types the same way once its running.  It sounds like you are concerned about the transaction type of deploy/invoke/query, not the chaincode type of golang/other/other.  I would imagine the transaction type field should remain present indefinitely .  In light of this new info, is this ok?

**Comment by adecaro** [comment]
@ghaskins Yes, it is fine :)

**Comment by srderson** [comment]
The first pass is changing `ChaincodeSpec.ctorMsg` to `ChaincodeSpec.input`.

**Comment by angrbrd** [comment]
@srderson can this issue be closed? Has this either been addressed or transitioned over to Gerrit? Please let me know. Thanks!

**Comment by srderson** [comment]
I'll recreate in Jira. Needs to be part of the new proto definitions.
