### ISSUE TITLE
Need a node.js crypto library

### ISSUE THREAD

**Issue by smithbk** [hyperledger-archives/fabric#1199]
This includes configuration options and ability to sign, verify, encrypt, and decrypt.

This is a prereq for #1134

**Comment by adecaro** [comment]
I think we need also EC math.

**Comment by smithbk** [comment]
Just to clarify, we need crypto functions that are currently in the NVP.  Any that are required in the VP but not the NVP are not needed in node.js.
Also, wanted to make sure you saw kdf.js for key derivation, which was written because no node module was found.

**Comment by thkzrl** [comment]
Node.JS makes some (most?) of the internally used OpenSSL functionality available at the Javascript level, including ECDH: https://nodejs.org/api/crypto.html  Let's check what's missing...

**Comment by smithbk** [comment]
Another consideration when choosing a crypto module is can it run in a browser using something like http://browserify.org ?   This is not the definitive consideration but should be weighed.  Other than using a native C library, I'm not sure what would prevent a node module from being browserified.

**Comment by adecaro** [comment]
@smithbk Indeed, if a non-validating peer is supposed to submit transactions then it needs to be able to compute maths over elliptic curve groups in order to successfully run the protocol to get TCerts from the TCA. 

Regarding the kdf: We actually use hmac directly when it is needed. An hmac-based kdf is used to implement the ECIES engine but this will be deprecated soon because it is non-standard.

Anyway, let's keep that code anyway. I'm sure it will be useful at some point :)

**Comment by mastersingh24** [comment]
would anyone be upset if the NodeJS SDK only worked with Node 4.x and higher (meaning no support for 0.10.x or 0.12.x)?  There are more crypto functions natively exposed on 4.x and higher than the previous versions

**Comment by ghaskins** [comment]
my requirements are cljs and electron...of this, i suspect electron is more of the issue....not sure what it uses.

**Comment by ghaskins** [comment]
I just checked, electron currently uses nodejs 5.x, so I think we are good from my perspective.

**Comment by rtang03** [comment]
nodejs 6.0.0 has built-in crypto, does it help?

**Comment by smithbk** [comment]
This is complete
