### ISSUE TITLE
How to get query chaincode after CLI deploy?

### ISSUE THREAD

**Issue by zhuang-weiming** [hyperledger-archives/fabric#1342]
First I saw:

[> The query request requires the client to supply a name parameter, which was previously returned in the response from the deploy transaction. The response to a query request depends on the chaincode implementation.](https://github.com/hyperledger/fabric/blob/master/docs/protocol-spec.md#6213-chaincode-api)

It needs name parameter, which was previously returned in the response from the deploy transaction.
If somebody uses CLI to deploy chaincode like below:
`./peer chaincode deploy -p github.com/hyperledger/fabric/example/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'`
How to get the hashing code returned in the response from the deploy transaction?

**Comment by zhuang-weiming** [comment]
And if the name --- hashing code is incorrect, the error message is as below:

```
HEADERS: {"access-control-allow-headers":"accept, content-type","access-control-allow-origin":"*","content-type":"application/json","date":"Wed, 04 May 2016 08:54:20 GMT","content-length":"117","connection":"close"}
DATA: {"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params","data":"Chaincode name may not be blank."},"id":1}
```

**Comment by corecode** [comment]
deploy should print the returned chaincode identifier.

**Comment by zhuang-weiming** [comment]
so the returned chaincode identifier is in the terminal of peer, it is not in the terminal of deploy command terminal, correct?

**Comment by corecode** [comment]
no, the deploy command should print the chaincode identifier

**Comment by zhuang-weiming** [comment]
No. chaincode hashing code did not show in any terminal .
![17777](https://cloud.githubusercontent.com/assets/7720620/15034241/0b1f85c8-12a6-11e6-95b6-d53092f862fa.JPG)

**Comment by adecaro** [comment]
Hi @WillZhuang, I think there is an issue in the way you use the CLI. @angrbrd, please correct me if I'm wrong. The '-n' parameter is used to specify the name of the chaincode not its path. This means that to invoke and query that deployed chaincode you have to use the name specified at deploy time.
You don't need the hashing code (aka chaincode id) anymore.

Notice that, in order to have this working, the chaincode should be already running somewhere and registered to the validator with the name you specify at deploy time. This is more or less the setting described in this document: https://github.com/hyperledger/fabric/blob/master/docs/API/SandboxSetup.md

**Comment by muralisrini** [comment]
@WillZhuang : assume this has been resolved for you ?

**Comment by angrbrd** [comment]
@WillZhuang are you running in development mode or network mode? It seems to me, from the snapshots above, that you are in network mode... The SandboxSetup.md instructions are specifically for running your chaincode locally in development mode. Development mode means that you are starting the chaincode locally and give it a name when you start it up. Then when you deploy/invoke/query it, you target that **name**. In network mode, you use the chaincode **path** for deployment to the network and then issue invoke/query by pointing to the **hash** that is returned from deployment. So to have your example in the snapshots work properly, you should use "-p" instead of "-n" as it seems to me that you are in network mode. Try this and the terminal in which you are deploying the chaincode should display a hash number. Let me know if this works for you.

./peer chaincode deploy -p /path/to/chaincode/directory -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'
