### ISSUE TITLE
'index out of range' panic using Sieve

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1368]
This is another failure mode of the setup described in #1366. Here is the tail of the log of the failing peer.

[logTail.txt](https://github.com/hyperledger/fabric/files/250691/logTail.txt)

**Comment by corecode** [comment]
@jyellick should we just use `append()` instead of pre-allocating that array?  I'll have to look longer to figure out how this happens.

**Comment by jyellick** [comment]
@corecode This is actually a bug because the Sieve thread is entering into `pbft-core.go` and modifying the state while the `pbft-core.go` thread is also doing so.  It causes the map size to change and produces this out of index bug.  This should be a straightforward fix, I'll submit a PR shortly.

Edit: Actually looks like you beat me to this one, should be fixed by your PR below.

**Comment by vukolic** [comment]
what's the status? can this one be closed?

**Comment by bcbrock** [comment]
@vukolic Yes, I haven't seen this in a while.
