### ISSUE TITLE
Error:Failed to launch chaincode spec(Failed to init chaincode(handler not found for chaincode xxx))

### ISSUE THREAD

**Issue by yeasy** [hyperledger-archives/fabric#1467]
## Description

With pbft consensus, without membersrvc, using `CORE_CHAINCODE_MODE=dev`.

Deploy chaincode is successful, but invoke or query it will fail with error msg:
`Error: Error querying chaincode: rpc error: code = 2 desc = "Error:Failed to launch chaincode spec(Failed to init chaincode(handler not found for chaincode xxx))"`
## Describe How to Reproduce

1) Start a hyperledger peer node or cluster with pbft as consensus following the documentation. No error msg if found at the peer nodes' output.
2) deploy chaincode example02 with

``` sh
$ CORE_CHAINCODE_MODE=dev peer chaincode deploy -n "test" -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'
07:36:35.690 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO
07:36:35.691 [logging] LoggingInit -> DEBU 002 Setting default logging level to DEBUG for command 'chaincode'
07:36:35.692 [peer] func1 -> INFO 003 Auto detected peer address: 172.17.0.5:30303
07:36:35.692 [peer] func1 -> INFO 004 Auto detected peer address: 172.17.0.5:30303
07:36:35.693 [peer] func1 -> INFO 005 Auto detected peer address: 172.17.0.5:30303
07:36:35.697 [main] chaincodeDeploy -> INFO 006 Deploy result: type:GOLANG chaincodeID:<path:"github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02" name:"test" > ctorMsg:<function:"init" args:"a" args:"100" args:"b" args:"200" >
test
```

3) query it:

``` sh
$ peer chaincode query -n "test" -c '{"Function": "query", "Args": ["a"]}'
07:36:49.568 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO
07:36:49.569 [logging] LoggingInit -> DEBU 002 Setting default logging level to DEBUG for command 'chaincode'
07:36:49.570 [peer] func1 -> INFO 003 Auto detected peer address: 172.17.0.5:30303
07:36:49.570 [peer] func1 -> INFO 004 Auto detected peer address: 172.17.0.5:30303
07:36:49.571 [peer] func1 -> INFO 005 Auto detected peer address: 172.17.0.5:30303

Usage:
  peer chaincode query [flags]

Flags:
  -x, --hex[=false]: If true, output the query value byte array in hexadecimal. Incompatible with --raw
  -r, --raw[=false]: If true, output the query value as raw bytes, otherwise format as a printable string


Global Flags:
  -c, --ctor="{}": Constructor message for the chaincode in JSON format
  -l, --lang="golang": Language the chaincode is written in
      --logging-level="": Default logging level and overrides, see core.yaml for full syntax
  -n, --name="": Name of the chaincode returned by the deploy transaction
  -p, --path="": Path to chaincode
  -u, --username="": Username for chaincode operations when security is enabled

Error: Error querying chaincode: rpc error: code = 2 desc = "Error:Failed to launch chaincode spec(Failed to init chaincode(handler not found for chaincode test))"
```

**Comment by mastersingh24** [comment]
@yeasy - when you use the CORE_CHAINCODE_MODE=dev flag, it will not actually build and deploy the chaincode in docker containers.   The purpose of "dev" mode is for you to be able to compile and run your chaincode without having to go through the full deploy cycle.

Now your situation is a little odd in that you are setting the flag while running the CLI to deploy, but this still results in the actual bytes of the chaincode not being physically deployed across the network

What are you hoping to accomplish with running in "dev" mode?

**Comment by yeasy** [comment]
@mastersingh24 
Thanks for the comments!
So in dev mode, we cannot deploy the chaincode. Then how can we run my own chaincode?
Could you help give the typical usage example with the dev mode?
Thanks a lot!

**Comment by muralisrini** [comment]
@yeasy : part of the confusion is the word "deploy".

In NON-dev mode, "deploy" does the following
- compute the chaincode package for creating images
- send the chaincode package to all peers
- each peer creates the image
- each peer starts the container
- the init function is sent to each container

As @mastersingh24 points out dev mode is meant to be run with 1 local peer. It is for testing / dev only.

First of all, one runs the peer with "--peer-chaincodedev" mode.

In dev mode, "deploy" does the following
- user starts the chaincode pointing to the peer
- the deploy function sends "init" to the above chaincode

ie, the only purpose of "deploy" in dev mode is to send the "init". 

Typical usage example for dev mode is in https://github.com/hyperledger/fabric/blob/master/docs/API/SandboxSetup.md

**Comment by yeasy** [comment]
@muralisrini 
Thanks for the comments.

So if I want to run the chaincode without container in the dev mode, is it possible to run the deploy, invoke, query steps?
Could you give some detailed steps?
Thanks!

**Comment by muralisrini** [comment]
@yeasy : Yes, that is possible. The steps for deploy, invoke and query in dev mode are in https://github.com/hyperledger/fabric/blob/master/docs/API/SandboxSetup.md. I would just be repeating them here. I'd go through "non-security" steps to get started.  But if you have more questions or need clarifications on the steps there, we could certainly talk further.

**Comment by yeasy** [comment]
@muralisrini Thanks for the comments. 
I will follow the steps first.

**Comment by rajaduggimpudi** [comment]
@muralisrini : I was trying to query transaction using the following command and see the following error 

peer chaincode query -n  <chainCodeHash> -c '{"Function": "query", "Args": ["a"]}' -u jim

23:52:59.542 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO
Usage:
  peer chaincode query [flags]

Flags:
  -x, --hex[=false]: If true, output the query value byte array in hexadecimal. Incompatible with --raw
  -r, --raw[=false]: If true, output the query value as raw bytes, otherwise format as a printable string

Global Flags:
  -c, --ctor="{}": Constructor message for the chaincode in JSON format
  -l, --lang="golang": Language the chaincode is written in
      --logging-level="": Default logging level and overrides, see core.yaml for full syntax
  -n, --name="": Name of the chaincode returned by the deploy transaction
  -p, --path="": Path to chaincode
  -u, --username="": Username for chaincode operations when security is enabled

Error: Error querying chaincode: rpc error: code = 2 desc = "Error:Failed to launch chaincode spec(Error starting container: cannot connect to Docker endpoint)"

I'm running peer in NON-DEV mode (mode: net). In net mode, validator will run chaincode in docker container. 

Brief summary of peer node log

23:14:57.568 [devops] invokeOrQuery -> DEBU 03c Initializing secure devops using context jim
23:14:57.568 [crypto] invokeOrQuery -> INFO 03d Initializing client [jim]...
23:14:57.682 [crypto] invokeOrQuery -> INFO 03e Initializing client [jim]...done!
23:14:57.682 [devops] createExecTx -> DEBU 03f Creating secure invocation transaction 774fd330-ed1f-4a4d-b472-15386f3b5505
23:14:57.683 [devops] invokeOrQuery -> DEBU 040 Sending invocation transaction (774fd330-ed1f-4a4d-b472-15386f3b5505) to validator
23:14:57.683 [peer] sendTransactionsToLocalEngine -> DEBU 041 Marshalling transaction CHAINCODE_QUERY to send to local engine
23:14:57.683 [peer] sendTransactionsToLocalEngine -> DEBU 042 Sending message CHAIN_TRANSACTION with timestamp seconds:1463786097 nanos:683657855  to local engine
23:14:57.950 [chaincode] getArgsAndEnv -> DEBU 043 Executable is /opt/gopath/bin/7849b0cdbc04a8498e3601188bf4ef87d25b5efda9d89cdb879914fcbbe544a429d379bdcb210e2ba7de131ee84b53b974e3afcbacbcf0e2db4ec408a4ddb568
23:14:57.950 [chaincode] launchAndWaitForRegister -> DEBU 044 start container: 7849b0cdbc04a8498e3601188bf4ef87d25b5efda9d89cdb879914fcbbe544a429d379bdcb210e2ba7de131ee84b53b974e3afcbacbcf0e2db4ec408a4ddb568(networkid:dev,peerid:vp0)
23:14:57.950 [container] lockContainer -> DEBU 045 waiting for container(dev-vp0-7849b0cdbc04a8498e3601188bf4ef87d25b5efda9d89cdb879914fcbbe544a429d379bdcb210e2ba7de131ee84b53b974e3afcbacbcf0e2db4ec408a4ddb568) lock
23:14:57.950 [container] lockContainer -> DEBU 046 got container (dev-vp0-7849b0cdbc04a8498e3601188bf4ef87d25b5efda9d89cdb879914fcbbe544a429d379bdcb210e2ba7de131ee84b53b974e3afcbacbcf0e2db4ec408a4ddb568) lock
23:14:57.950 [dockercontroller] Start -> DEBU 047 Cleanup container dev-vp0-7849b0cdbc04a8498e3601188bf4ef87d25b5efda9d89cdb879914fcbbe544a429d379bdcb210e2ba7de131ee84b53b974e3afcbacbcf0e2db4ec408a4ddb568
23:14:57.950 [dockercontroller] stopInternal -> DEBU 048 Stop container dev-vp0-7849b0cdbc04a8498e3601188bf4ef87d25b5efda9d89cdb879914fcbbe544a429d379bdcb210e2ba7de131ee84b53b974e3afcbacbcf0e2db4ec408a4ddb568(cannot connect to Docker endpoint)
23:14:57.950 [dockercontroller] stopInternal -> DEBU 049 Kill container dev-vp0-7849b0cdbc04a8498e3601188bf4ef87d25b5efda9d89cdb879914fcbbe544a429d379bdcb210e2ba7de131ee84b53b974e3afcbacbcf0e2db4ec408a4ddb568 (cannot connect to Docker endpoint)
23:14:57.951 [dockercontroller] stopInternal -> DEBU 04a Remove container dev-vp0-7849b0cdbc04a8498e3601188bf4ef87d25b5efda9d89cdb879914fcbbe544a429d379bdcb210e2ba7de131ee84b53b974e3afcbacbcf0e2db4ec408a4ddb568 (cannot connect to Docker endpoint)
23:14:57.951 [dockercontroller] Start -> DEBU 04b Start container dev-vp0-7849b0cdbc04a8498e3601188bf4ef87d25b5efda9d89cdb879914fcbbe544a429d379bdcb210e2ba7de131ee84b53b974e3afcbacbcf0e2db4ec408a4ddb568
23:14:57.951 [dockercontroller] createContainer -> DEBU 04c Create container: dev-vp0-7849b0cdbc04a8498e3601188bf4ef87d25b5efda9d89cdb879914fcbbe544a429d379bdcb210e2ba7de131ee84b53b974e3afcbacbcf0e2db4ec408a4ddb568
23:14:57.951 [dockercontroller] Start -> ERRO 04d start-could not recreate container cannot connect to Docker endpoint
23:14:57.951 [container] unlockContainer -> DEBU 04e container lock deleted(dev-vp0-7849b0cdbc04a8498e3601188bf4ef87d25b5efda9d89cdb879914fcbbe544a429d379bdcb210e2ba7de131ee84b53b974e3afcbacbcf0e2db4ec408a4ddb568)
23:14:57.951 [chaincode] LaunchChaincode -> DEBU 04f launchAndWaitForRegister failed Error starting container: cannot connect to Docker endpoint
23:14:57.951 [crypto] CloseClient -> INFO 050 Closing client [jim]...

Question here being why is the container being taken offline aka terminated ?
