### ISSUE TITLE
Consensus: Deploy does not goes through on all peers after pausing one of the peers

### ISSUE THREAD

**Issue by 2016Nishi** [hyperledger-archives/fabric#1472]
## Description

After an initial deployment on 5 peer network, paused PEER4, and deployed another chaincode from PEER0. It was observed that PEER0 does not get new chaincode deployment even after waiting 30min, by running 'docker ps -a' command.
## Describe How to Reproduce
1. Setup a 5 peer node with security using docker commands
2. Deploy chaincodeexample02 with args {"a", "100", "b", "200"} using Postman or any other tool.
3. Issue 'docker ps -a'
4. Observe that all 5 peers have chaincode containers deployed inside docker
5. Issue 'docker pause PEER4'. PEER4 is now in paused state.
6. Deploy chaincodeexample02 with args {"a", "10", "b", "20"} using Postman or any other tool from say PEER0
7. Issue 'docker ps -a' (waited more than 30 min 
8. Notice that PEER1, PEER2, PEER3 receive new container chaincode deployed.
9. But PEER0 does not have a chaincode container deployed inside docker as expected.

P.S. We can help setup the environment to reproduce the scenario.

Build: e108db6

**Comment by corecode** [comment]
Is this a duplicate of #933?  If so, please close this issue.

**Comment by 2016Nishi** [comment]
#933 is related to invoke. In our test scenario 'Deploy' of chain code was not happening on the Peer from where Deploy request was issued, when we had one peer in paused state.

**Comment by corecode** [comment]
For the fabric there is no difference between deploy and invoke.

**Comment by 2016Nishi** [comment]
Since we have a similar issue #933 on invoke, closing as per comments above.

**Comment by harrijk** [comment]
@corecode @2016Nishi ...I understand that this issue is closed, but I wanted to add my observations to this issue.  In terms of the syncing of state, I agree that deploy and invoke behave in the same manner.  However, I have observed additional behaviors with regards to deploying chaincode while one of the peers is down (and started back up) that may not be expected...

**Observation**: The peer that was stopped/paused and then started/unpaused never does create a docker image (and container) for the chaincode of the 2nd deploy transaction.  

Here is a test scenario that I ran:
1. Start 5 peers with security enabled with pbft consensus.
2. Run deploy transaction.  All 5 peers successfully execute the deploy transaction.
3. Run 10 invoke transactions.  All 5 peers are in agreement with respect to blockchain height and block hashes.
4. Shutdown vp1.
5. Run a new deploy transaction.  The remaining 4 peers successfully execute the 2nd chaincode deploy transaction. 
6. Run 10 invokes on the 2nd deployed transaction. All 4 remaining peers are in sync in terms of chain height and block hashes.
7. Start vp1.
8. Run continuous invoke transactions on the 2nd deployed transaction at a rate of 1 invoke per second.
9. vp1 occasionally catches up in chain height with matching block hashes, but still lags behind.  The peer,  vp1, still does not have a docker image and container for the 2nd deployed transaction. 
10. Stop vp3 to allow vp1 to sync with the remaining 4 peers.  vp1 syncs and stays in sync with remaining 4 peers in terms of chain height, however, vp1's currentBlockHash and previousBlockHash do not match the other peer chain hashes when comparing the same block number.  The peer,  vp1, still does not have a docker image and container for the 2nd deployed transaction. 

After running invokes on the 2nd deployed transaction for about an hour, the hashes of vp1 matched the hashes of the other peers when comparing the same (later) block numbers, but  exhibited a "lagging" behavior, i.e., always several blocks behind (normal behavior).  The peer, vp1, still did not have a docker image and container for the 2nd deployed transaction.

I'm trying to understand why the chaincode is never deployed to my vp1 peer even though it seems to be happy with "almost" being in sync with the other peers.

**Build**: `c6628c`

**Comment by corecode** [comment]
@muralisrini is this some interaction between state transfer and chaincode?  Maybe we need to open a specific issue about this.

**Comment by muralisrini** [comment]
@corecode yes, that is a different problem. We need to create the image on invoke/query if one does not exist. 

@harrijk we could open a new issue or just change the title to something like "chaincode image need to be created if one does not exist".
