### ISSUE TITLE
Logic behind `docker-compose-files` folder

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#1548]
## Description

I'm not sure I get the logic behind the `fabric/consensus/docker-compose-files` directory being how it is today, and the included Markdown file (which should probably be moved to the Wiki) doesn't really clarify things.

This directory currently has nine YAML files.

I see the need for `compose-consensus-4-{batch, classic, sieve}.yml` so we're three files down - good. Based on what I read in the Markdown file, `compose-consensus-4.yml` is actually the, err, true `docker-compose.yml` and it extends `compose-consensus-4-defaults.yml`. So:
- `compose-consensus-4-batch.yml`
- `compose-consensus-4-classic.yml`
- `compose-consensus-4-sieve.yml`
- `compose-consensus-4-defaults.yml`
- `compose-consensus-4.yml`

Are accounted for.
## Questions
1. What role does the _existing_ `docker-compose.yml` (and `compose-defaults.yml`) serve?
2. Is there a reason why we're keeping `compose-consensus-4-links.yml` in a separate file and we don't merge it with `compose-consensus-4-defaults.yml`?
## Expected Behavior

As a developer, I would expect the `docker-compose.yml` file to do what `compose-consensus-4.yml` and `compose-consensus-4-links.yml` currently do.

There's always a chance I'm missing something.

**Comment by bcbrock** [comment]
@kchristidis I would ask a more general question - Why do we store any Docker-compose files in this repository at all?

The `peer` and `memberservc` networks we create are so uniform and consistent that they could/should all be created by the application of a single script, which would generate and then execute a custom Docker-compose file based on the user's requirements. Creating a Docker-compose network of 39 peers running Sieve consensus with security and profiling should be as simple as executing

```
dockerComposeNetwork -security -sieve -profile 39
```

For an existence proof of this approach see the **busywork** script [userModeNetwork](https://github.com/hyperledger/fabric/blob/master/tools/busywork/bin/userModeNetwork)
which supports the above (using simple processes rather than containers), plus correctly handles the startup sequencing issues discussed in #1234, and also creates a JSON encoding of the network configuration for use by other tools.

**Comment by tuand27613** [comment]
The fabric/consensus/docker-compose-files are leftovers from obc-peer when we needed a way to startup 4 peers for unit testing. corecode started with docker-compose.yml and compose-default.yml. tuand27613 copied from those 2 and created the compose-consensus-4 files. 

If we don't see the need for these anymore,  I've got no issues with nuking from the repo.

**Comment by tuand27613** [comment]
@rameshthoomu  @bmos299  ^^^
