### ISSUE TITLE
TDD and BDD frameworks for Fabric

### ISSUE THREAD

**Issue by JonathanLevi** [hyperledger-archives/fabric#1589]
## Description

Fabric currently has a set of integration/Behavior-Driven/Feature harnesses that work quite nicely for testing REST API and JSON (JavaScript Object Notation) output testing and manipulation, using [Behave](https://behave.github.io/behave.example), the "[cucumber](https://cucumber.io/docs)-clone for Python" (as their web-site suggests).
## Background

Behavior-driven development (or BDD) is great, as it "encourages collaboration between developers, QA and non-technical or business participants in a software project".

Keeping the ability to describe scenarios in high-level, using a human-readable and parseable grammar (aka, "natural words") makes it easy for non-technical or business participants to also take a more active part, etc.
## Context

The question is whether we should use Behave which is Python based/backed, rather than other frameworks (e.g., something that is written in Golang, which will allow us to work with the objects/API natively) - I am thinking beyond (or actually, below) the REST API.

I am genuinely asking, as I haven't been privy to earlier discussions that lead to Behave, and I wonder what other frameworks we could look into, that will make it easy to test Fabric's REST API as we do today, but will offer more (with/without the need for other to learn other programming/scripting languages).

While keeping the good BDD-features and the Cucumber-style syntax for the acceptance tests from the angle of the developers/QA people: shall we try other frameworks (for example, some that are written in Golang?
## Alternatives

Of course this is not to imply/suggest that it is mandatory/necessary to use Golang for testing the orchestration/external-api layer - the current Behave test using Python's `requests` and `json` packages are doing great for the REST API, and the Python code/script there is not that complex.

Thinking out loud here (issue came up when discussing Python vs Golang, even though I'm a Python developer myself). Mainly in terms of barrier to entry for other Golang devs - discussion/suggestions welcome!

Trying to gauge interest: what, for example, are the current/latest thoughts on [Ginkgo](https://github.com/onsi/ginkgo) / [Gomega](https://onsi.github.io/gomega) ?

**Comment by srderson** [comment]
For background, @jeffgarratt picked Behave and wrote the initial BDD testing implementation that Fabric is using. I'm guessing he picked Behave because that's what he had used in the past and it allowed him to quickly get something working. I'll let @jeffgarratt comment as to other reasons why he may have picked Behave and whether there are any technical differences.

**Comment by jeffgarratt** [comment]
@JonathanLevi @srderson Behave was chosen due to past experience as well as the ability for testers to write new tests without the knowledge of the internals or even golang (or any language for that matter).  I looked at golang BDD frameworks hoping to port some to validate, but quickly ran into the now you must know a language to even get started (Ginko).  I do think it is worth while to investigate these options, and I believe they can be integrated with little difficulty.  I just find that each time I start to investigate, I have to work on some system function, and the behave stuff is there and just works.  But as we become more sophisticated, these other tools may prove very useful.

**Comment by christo4ferris** [comment]
@jeffgarratt I can appreciate the thinking behind a BDD framework that non-developers can use to write tests without knowing golang. However, this misses the whole point of BDD/TDD, IMO. The **developers should be writing the tests**. They should be writing failing tests **first**, ideally and then writing code to make them pass. You can do this with behave and go, but that involves running the whole suite of tests when you are just refactoring or adding one new feature. If we were relying on a golang based testing framework, you could add a watch (many support this) and have tests run automagically just for the package to see how you are progressing. Much less time wasted waiting for the full suite of tests to run.

Yes the behave stuff is just there, but as noted, it pulls in additional dependencies on the development environment and it also means that to extend/maintain the DSL we need mad Python skillz.

**Comment by christo4ferris** [comment]
closing this as I think we are where we are. We can revisit at a later time when we have more arms and legs

**Comment by JonathanLevi** [comment]
And in the meantime, thank you for #1772!
