### ISSUE TITLE
Upgrade github.com/op/go-logging package

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#1670]
## Description

Upgrade the `github.com/op/go-logging` package to the latest version.
##### The easy part

From Vagrant

```
cd $GOPATH/src/github.com/hyperledger/fabric
go get github.com/op/go-logging
govendor update github.com/op/go-logging
```
##### The hard part

The API has changed such that `Info(...)`, `Warning(...)`, `Error(...)`, etc. functions now have `Infof(...)`, `Warningf(...)`, `Errorf(...)` equivalents. These functions are referenced in many locations.

The motivations behind this upgrade are
1. To get the latest and greatest
2. Eliminate many `go vet` warnings caused by the current API

Adding a help wanted tag to this if anyone is interested. Otherwise I may tackle this.

**Comment by genggjh** [comment]
@srderson, I can do this. Assign it to me.

**Comment by corecode** [comment]
if gorename can deal with vendored repos by now, it could be an easy way to change all calls.

**Comment by genggjh** [comment]
@corecode good suggestion, I will try it.

**Comment by srderson** [comment]
@genggjh You got it, thanks!

**Comment by bcbrock** [comment]
Hi @genggjh - May I offer to put more work on your plate? When I implemented the logging APIs for chaincodes, I only implemented the 'f' versions, to avoid confusion with the old op/go-logging conventions   used by the fabric code which I suspected would change one day. Since you're mucking with logging anyway, would you mind extending this issue to add the non-f versions of the shim logging functions as well? Then all go codes will be in sync and using the same naming conventions.

**Comment by genggjh** [comment]
@bcbrock, I got your point, but should be in a separate PR after we merge this big changes.

**Comment by genggjh** [comment]
@bcbrock, I got your point, for add non-f logging functions into the shim, I think we need a separate PR after we merge this big changes.

**Comment by genggjh** [comment]
@srderson pls help to review my changes.
