### ISSUE TITLE
Add support for environment variables on consensus

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#171]
Move the consensus-related variables from `/openchain.yaml` to `/openchain/consensus/pbft/config.yaml`.

Add support for environment variables using the `viper` package. When the user runs `obc-peer` with an environment variable that is prefixed with, say, `OPENCHAIN_CONSENSUS_X`, the value of that variable should overwrite the value of variable `x` in `pbft/config.yaml`.

Use the `viper` plugin and mimic the existing logic in `main.go`. Edit `main.go` as necessary.

**Comment by jyellick** [comment]
Adding the env support via Viper looks pretty straightforward, but I had some questions on moving the consensus related vars out of the main yaml.  

In particular, the current peer.consensus.\* variables are used in both main.go and validator.go, and I don't see how either of them get access to the Plugin struct in pbft.  I've actually been struggling to figure out that code path generally, as best as I can tell, validator pulls in pbft, which in turn pulls in controller which invokes pbft.New, which is then stored in such a way that it is only accessible through GetHelper, which I never see invoked anywhere.

I'm also not 100% sure on why the config is under pbft, and not under consensus more broadly, as it seems like this config would have implications for other consensus plugins as well.  For instance whether a peer is validating or not (which I read as whether it does consensus at all or not).  

The leader vars I'm thinking are placeholders, since pbft will do its leader elections itself, so I imagine those will transition to a more general peer list down the line? (Which I think would be applicable to all consensus algorithms? Though maybe not)

**Comment by kchristidis** [comment]
Good questions, I'll start from the bottom and move my way up.
1. On why `config.yaml` belongs to the `plugin` package, and not the `consensus` one. That's how I had designed it originally, but Binh has rightly argued that the consensus layer should be as thin as possible. What if you have a consensus algorithm that's so simple that doesn't need a `config` file? By moving config to an earlier level in the stack, we're forcing every plugin developer to provide one. As Binh said, we don't want that.
2. The `leader` var in the config is indeed a placeholder until we allow dynamic leader election. Since we do need it for now, it's a good use case to drive the development of this issue, i.e. make it so that we're able to set a (static) leader from the command line. (Don't worry about the fact that if we set two leaders on the network all hell will break loose. Think happy path for now, we'll add complexity later.)
3. Regarding your first point: One, keep in mind that `validator.go` and `leader.go` will be deleted quite soon. The only useful thing in there is the FSM (which is still rough and full of placeholders); and that FSM will be moved to the placeholder I've already created in the `plugin` package. Two, the way things work are: a peer is launched and registers a message handler. When this message handler sees an incoming `openchainmessage_consensus` or `openchainmessage_request` message coming in, they route this message to our `consensus` layer, which in turns routes it to the `plugin` (or, in our case `pbft`) package. This mechanism is more or less already in place, but Binh and Jeff are working on make it work exactly as I described. With that in mind, is there any reason for consensus-related variables to reside on `openchain.yaml`? If there is (and this makes sense for the product in general) then I'm fine with it; just let me know what you think should remain there.

**Comment by jyellick** [comment]
Thanks for the clarification.

Points 1 and 2 make good sense.

With respect to point 3, I'm not sure what the timeframe on deleting `validator.go` and `leader.go`, but does it seem reasonable to leave those config variables in the `openchain.yaml` with a comment deprecating their use?  If there is an issue open for the deletion of those two files, perhaps we could add a comment there to ensure they are deleted from the main config once they are no longer needed.

It will depend on how exactly how the future flow is supposed to proceed, but a logical configuration hierarchy to me would be to specify the consensus algorithm in the `openchain.yaml`, and rather than support the `validating` property, instead require that the `noop` validator be specified.  This would avoid the confusion of specifying a pbft consensus but also turning off validation.  If running pbft without validation still makes sense, then that validation flag would make sense to move into consensus yaml.

Let me know about your thoughts on leaving/deprecating those variables are, and I'll put together a changeset.

**Comment by kchristidis** [comment]
Good points. As the timeframe for these changes is still a bit unclear, here's a much simpler task to begin with.

I want to launch `obc_peer` with an `OPENCHAIN_PBFT_x` flag, and I want the value of that flag to overwrite the value of variable `x` specified in `pbft/config.yaml`.

We'l use that to modify timeout parameters on the fly.

Let me know if that makes sense, or if more clarifications are needed.
