### ISSUE TITLE
Dockerfile content is in config file

### ISSUE THREAD

**Issue by esgott** [hyperledger-archives/fabric#1745]
The configuration file (core.yaml) contains the recipe for the docker image. I suppose, the config file is for storing runtime configuration parameters, and the running application doesn't need this information (am I right in this?). As I see, images are created from go tests only, however, they could be created with `docker build` from the Makefile, with static `Dockerfile`. It would make it much more easier to understand the build process.

**Comment by ghaskins** [comment]
See PR #1708

**Comment by esgott** [comment]
Didn't see that.

**Comment by ghaskins** [comment]
No problem, that was an FYI.  As a side note, the fabric still needs to manage some of the Dockerfiles since docker is used as a component of chaincode isolation.  So, even after the above referenced PR, there will still be some Dockerfile info in the YAML, but IMO this is ok.  I think the main points you reference are handled as part of #1708
