### ISSUE TITLE
Consolidate duplicate/bespoke CBCEncrypt/CBDecrypt implementations

### ISSUE THREAD

**Issue by JonathanLevi** [hyperledger-archives/fabric#1780]
## Description

Just spotted some AES code duplication in [fabric/membersrvc/ca/util.go](https://github.com/hyperledger/fabric/blob/5dfbf946e158791b9934f3880907f21f8dd7f796/membersrvc/ca/util.go) specifically [CBCEncrypt](https://github.com/JonathanLevi/fabric/blob/ca8135b1a0f95127c96478518628a65a377ec123/core/crypto/primitives/aes.go#L68-L98) and [CBCDecrypt](https://github.com/JonathanLevi/fabric/blob/ca8135b1a0f95127c96478518628a65a377ec123/core/crypto/primitives/aes.go#L100-L134). 

At the same time, we are also sharing the AES functionality and wrappers here [core/crypto/primitives/aes.go](https://github.com/JonathanLevi/fabric/blob/ca8135b1a0f95127c96478518628a65a377ec123/core/crypto/primitives/aes.go#L68-L98), specifically [CBCEncrypt](https://github.com/JonathanLevi/fabric/blob/ca8135b1a0f95127c96478518628a65a377ec123/core/crypto/primitives/aes.go#L68-L98) and [CBCDecrypt](https://github.com/JonathanLevi/fabric/blob/ca8135b1a0f95127c96478518628a65a377ec123/core/crypto/primitives/aes.go#L100-L134).
## Describe How to Resolve

We should use only the shared functions in [core/crypto/primitives/aes.go](https://github.com/JonathanLevi/fabric/blob/ca8135b1a0f95127c96478518628a65a377ec123/core/crypto/primitives/aes.go#L68-L98), have one implementation, update existing calls to use the shared one, write some tests to verify this [especially as these 2 implementations are not identical] and remove the duplicate from the good ol' `fabric/membersrvc/ca` code.
## Good First Bug

I consider this a **Good First Bug** especially for those in the community who would like to pick up a coding task and get involved in fabric, build it, test it, and learn how to contribute to it. Need this done quickly and will be happy to spend some time guiding (pointing to the right Wiki's mostly), and verifying this all the way to submitting the PR [ usually at the modest tuition charge of 1-2 `MoreTests` digital currency ;-) ]

Interested? Hit me/us here, or on [HL's Slack](http://hyperledgerproject.slack.com/jonathanlevi)

**Comment by JonathanLevi** [comment]
tags: `security`, `help wanted`, `good first bug`

**Comment by starsheriff** [comment]
I'd happy to volunteer, as discussed on slack

**Comment by JonathanLevi** [comment]
@starsheriff: This is all yours.

@binhn has extended an invite via email to join https://github.com/hyperledger - once joined, this will be assigned to you. Thanks guys.

**Comment by starsheriff** [comment]
@JonathanLevi @binhn I got the invite and joined the project.

**Comment by starsheriff** [comment]
Hei, 
since I am new to the project and also to go. Here are my first thoughts about this issue.
1. Basically, the methods CBCEncypt and CBCDecrypt in `crypto/primitives` and `membersrvc/ca` are identical. The only difference I could see is that the implementation in `ca` is padding the plain text to a multiple of the block size using `PKCS5Pad`.
   
   In `crypto/primitives` there is only a comment saying that could be done. _I would propose to implement it now._
2. What to test. I am not sure if there is a common style on how, and to which details you should test in `go` or if we follow a specific scheme in this project. Here are my thoughts of what we should test, including some comments/questions for the respective tests:
   1. CBCEncrypt is deterministic. Using same key, same IV --> identical cipher.
   2. change one bit in plain text --> more than x% bits changed in cipher (not sure if necessary)
   3. raises ciphertext to short error. Not sure how to test without mocking.
   4. raises "ciphertext length is not a multiple of the block size" error
   5. called stdlib function `cipher.NewCBCEncrypter(blk, iv)` with correct parameters (again not sure how to achieve)
   6. encrypt manually, then test decrypt
   7. encrypt,  then manually decrypt
   8. test that plain text is padded
      - plain text with length 1 byte
   9. test what happens with a zero length string (only null byte in string)
   10. check that IV is added to cipher (implicitly covered by higher level tests)
   11. check that cipher length is correct. (implicitly covered by higher level tests)
   12. check that padding is removed
3. Dependency Injection: What do you guys think to inject some dependencies to allow for more testing. It goes at the cost of readability (in my opinion). Any preferences? I am thinking of something of this style http://stackoverflow.com/questions/19167970/mock-functions-in-go

**Comment by binhn** [comment]
@JonathanLevi @starsheriff First, welcome starsheriff (we'll meet someday when I travel the galaxy:-)

Just a note that these functions are used in 2 different places: membersrvc  and peer.  Peer is a client of Membersrvc. They can definitely share code but must be copied and built into 2 separate executables.

**Comment by starsheriff** [comment]
Thanks @binhn, yes the approach we were taking was to look into the differences between the two implementations... There wasn't a need to really have another copy in membersrvc/util.go... as the only difference which was the padding is not relevant. I have been working with @jonathanlevi on the test cases to make sure that we can remove the other instance (so that both libraries share the same code that lives under primitives.

**Comment by starsheriff** [comment]
Hi, 
essentially PR #2051 did remove duplicated code. What was left to do now is some testing. I have discussed with @JonathanLevi and I believe we are ready to start a PR. As PR #2093 addresses the issue with the PKCS7 padding adding an extra block, we leave that out. Depending on the order of the PR's we will need to adjust the tests. Currently we are testing that this extra block is added because that's the master we are working on.

**Comment by JonathanLevi** [comment]
We now have one implementation of both of these functions, with a bunch of tests.

Closing this following #2051 and @starsheriff's recently merged PRs for [#2135 Add AES PKCS7 Padding/Unpadding Tests](https://github.com/hyperledger/fabric/pull/2135) and yesterday's [#2166 [AES-CBC] Add more unit-test to cover edge cases (with & without PKCS#7)](https://github.com/hyperledger/fabric/pull/2166).

Thanks again!
