### ISSUE TITLE
Consider removing logging wrapper functions from chaincode.go

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#1815]
## Description

`chaincode.go` contains functions such as `Debugf`, `Infof`, etc. The comment associated with these was

```
// Note: We're only creating the 'f' forms of the logging functions here for
// consistency with Go language conventions around formatted I/O routines, and
// to avoid confusion with the conventions used in the core code. It is
// possible that some day the core code will also change from using
// logger.Debug() to logger.Debugf() etc., and we want to protect chaincode
// writers from that hiccup if it occurs.
```

The core code will not support `Debugf`, `Infof`, etc. because we are upgrading the logging package. We can remove this wrapper or leave it we think it will continue to protect chaincode writers from future logging changes.

Personally, I'm somewhat tempted to leave it because
a) Some people have already used it
b) It will continue to protect chaincode writers from future logging changes.

**Comment by bcbrock** [comment]
I think we should leave the wrapper because it guarantees that the chaincode logs will appear correctly interleaved with the shim logs, and similarly formatted. If chaincodes simply import "op/go-logging", then depending on how the chaincode is built it could actually be loading a different binary version of the package with its own unique settings. Chaincode writers are always free to log however they want, this wrapper does not change that.

What we should do now is to add the non-f forms to the wrapper.

**Comment by genggjh** [comment]
I prefer to keep them and add non-f wrapper. Let cc developer use this wrapper, it will help us unify log formatter and easy debug.

**Comment by genggjh** [comment]
If all of us aggree with that, pls assgin this issue to me and I will work on non-f part.

**Comment by JonathanLevi** [comment]
Yes, +1 for leaving the f wrappers in...

**Comment by christo4ferris** [comment]
hmmm... I'm actually not in favor of keeping... it is just additional code we need to maintain and it is also a convention that we don't have throughout the whole codebase. This makes things more complex for someone joining the project.

**Comment by bcbrock** [comment]
@christo4ferris One of my points is that chaincodes are _not_ part of the codebase. They are independent of the peer implementation. I would argue that this makes it easier for someone joining the project as a chaincode developer because they don't need to read the Go source code to figure out how to log, they just need to read the documentation about the chaincode logging APIs. Presumably there will be many, many mode chaincode writers than peer maintainers. So yes, it may be seen as a bit more complicated by a few peer maintainers, but it is better for the few to suffer than the many.

**Comment by bcbrock** [comment]
@genggjh I will take the task of adding and documenting the non-f forms. Chris and I chatted in private and he agreed to the change and asked me to add some documentation to the source code.

**Comment by genggjh** [comment]
@bcbrock got it. thx.

**Comment by christo4ferris** [comment]
@bcbrock is this still relevant? Can it be closed?

**Comment by bcbrock** [comment]
yes it can be closed

**Comment by christo4ferris** [comment]
thanks!
