### ISSUE TITLE
Print version info

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#1959]
We'll need a way to print the version info using the `peer` binary.

The expected behavior is that `peer version`, `peer -v`, and `peer --version` should return version info by reading the `peer.version` key in the `core.yaml` file and quit.

This is a fairly straightforward task and a good opportunity for someone to get their hands wet with submitting patches to the project. They'll be using the [cobra](https://github.com/spf13/cobra), [viper](https://github.com/spf13/viper), and [pflag](https://github.com/ogier/pflag) packages.

@srderson If you agree, can we add the "Help wanted" tag to invite participation?

**Comment by GrapeBaBa** [comment]
@kchristidis @srderson Assign to me:)

**Comment by srderson** [comment]
Thanks @GrapeBaBa, you got it

**Comment by christo4ferris** [comment]
Thinking about this... seems like the API should also report peer version info so we can detect incompatible versions... this could be independent, but seems like we would need this once we are live in the field.

**Comment by JonathanLevi** [comment]
Yes, I may have an idea/suggestion of how to put some more info into the version which would tremendously help.

@GrapeBaBa, your issue ;-), but happy to collaborate, and suggest/would like to have it in Membership Services' server too. Will quickly add/introduce some command line/prompt parameters so that we can do/use this in the server too.

**Comment by GrapeBaBa** [comment]
@christo4ferris Glad to add it to API once I fix this issue.

**Comment by GrapeBaBa** [comment]
@JonathanLevi Will do. Ping me a slack when you are online.

**Comment by GrapeBaBa** [comment]
Just note #1962 ,the decision will impact this issue.

**Comment by mastersingh24** [comment]
@GrapeBaBa  - We should probably be a little more clear in #1962.  I did not mean that we get rid of every command line option, just the ones which specifically override / set configuration parameters.  Having a way to output version would be a good example, although I think you would have either `peer -v` and `peer --version`  or you would `peer version`.  I don't think we should mix styles

**Comment by GrapeBaBa** [comment]
@mastersingh24 Clear. @kchristidis @srderson @JonathanLevi @christo4ferris what do you think about the advice which not mix styles?

**Comment by kchristidis** [comment]
FWIW, `git` does both `git version` and `git --version`. And `docker` does all three. So there is definitely a mixing of styles going in on the industry. I am not an expert on this, so I don't have a strong take.

**Comment by GrapeBaBa** [comment]
I found a issue is that two logger always print. After investigation, that caused by two file use logger in init function, but logger hook set in peer main function. As init function will invoke before main function, that will always print.

I am not sure if this should be fixed or remain, I feel it is a little bit for printing version. Is it better only show version information? @kchristidis @srderson what about your thoughts?

```
vagrant@hyperledger-devenv:v0.0.10-5677e9c:/opt/gopath/src/github.com/hyperledger/fabric/peer$ ./peer version
2016/07/08 10:04:42 Load docker HostConfig: &{Binds:[] CapAdd:[] CapDrop:[] ContainerIDFile: LxcConf:[] Privileged:false PortBindings:map[] Links:[] PublishAllPorts:false DNS:[] DNSSearch:[] ExtraHosts:[] VolumesFrom:[] NetworkMode:host IpcMode: PidMode: UTSMode: RestartPolicy:{Name: MaximumRetryCount:0} Devices:[] LogConfig:{Type: Config:map[]} ReadonlyRootfs:false SecurityOpt:[] CgroupParent: Memory:0 MemorySwap:0 MemorySwappiness:0 OOMKillDisable:false CPUShares:0 CPUSet: CPUSetCPUs: CPUSetMEMs: CPUQuota:0 CPUPeriod:0 BlkioWeight:0 Ulimits:[]}
10:04:42.288 [crypto] main -> INFO 002 Log level recognized 'info', set to INFO
Peer server version 0.1.0
```

**Comment by kchristidis** [comment]
@bcbrock and I have reported this inconsistency in #769. It's not clear to me why the `crypto` package does its own thing. And I don't understand the need to always have that `docker Hostconfig` statement printed out.

**Comment by GrapeBaBa** [comment]
Why the issue still open?Can anyone fix it?

**Comment by GrapeBaBa** [comment]
@JonathanLevi Would you agree that i create another PR to have it in member srvc? As I see it need a little more work for member srvc.

**Comment by JonathanLevi** [comment]
@GrapeBaBa Yes, certainly. We might need a few probably. First, supporting command-line parameters in the first place, then having the version info, and of course to provide it. I/we can document these in issues, so that you can PR cleanly against these. Sure!

**Comment by juliancarrivick-ibm** [comment]
@GrapeBaBa @kchristidis I'm looking at issue #769 now

**Comment by GrapeBaBa** [comment]
@juliancarrivick-ibm Per @bcbrock explained the logging mechanism, it seems need remove the crypto in config.yaml and code below in crypto_settings.go

``` golang
    // Init log
    log.ExtraCalldepth++

    level, err := logging.LogLevel(viper.GetString("logging.crypto"))
    if err == nil {
        // No error, use the setting
        logging.SetLevel(level, "crypto")
        log.Infof("Log level recognized '%s', set to %s", viper.GetString("logging.crypto"),
            logging.GetLevel("crypto"))
    } else {
        log.Warningf("Log level not recognized '%s', defaulting to %s: %s", viper.GetString("logging.crypto"),
            logging.GetLevel("crypto"), err)
    }
```

**Comment by GrapeBaBa** [comment]
Just discussed with @JonathanLevi , and we are going to create a set of issues on the membership services side, separately... and I will use this only for a pull request (PR) for the  client at this point

**Comment by pjmorris** [comment]
Question: Should version track the version of the code at build time or at run time? As implemented, the version reports what's in core.yaml, so it will report whatever core.yaml has to say at run time, e.g.:

peer$ ./peer --version
Fabric peer server version 0.1.0

peer$ vi core.yaml  # change version to 0.2.0

$ ./peer --version
Fabric peer server version 0.2.0

Tracking the build time version of the code might help debugging issues where the peer (or membersrvc) code is a different version than expected.  
One means of implementing setting version at runtime would be to add a variable to the peer's main.go and set it via the -X flag, e.g.: 

main.go:

```
var (
        stopPidFile string
        **build_version string**
)
...
func showVersion() {
        version := viper.GetString("peer.version")
        fmt.Printf("Fabric peer server version %s\n", version)
        fmt.Printf("Fabric peer server build version %s\n", build_version)
}
```

and set the variable at build time:

```
go build -ldflags '-X main.build_version=0.1.0’   # could even grab value from core.yaml at this point
```

yielding... 

```
$ ./peer --version
Fabric peer server version 0.2.0
Fabric peer server build version 0.1.0
```

If the peer and core.yaml never change separately, the current behavior is great.  If there are points where they vary seperately, consider the ldflags alternative.

**Comment by christo4ferris** [comment]
@pjmorris good point. We really should be tracking a bunch of metadata. tag, commit sha, maybe date for added clarity. This could be added at build-time, maybe in a separate piece of yaml from core.yaml (only so that it isn't inadvertently stomped on, also makes it easier to update automatically, as it can simply be over-written at build-time. It could be baked into Docker images as environment variables or command-line flags, I suppose, but then what to be done when testing outside of the docker container? IMO, best to set this at build. @ghaskins @srderson thoughts?

**Comment by JonathanLevi** [comment]
I think build-time, with extended information - yes, with the -X option (injecting/setting the variable as part of the build script).

**Comment by pmorrisonfl** [comment]
@christo4ferris  My ulterior motive in raising this issue is to add the git repo/branch/sha as either a debug log message or perhaps as part of the version message.  We had a situation last week where troubleshooting would've gone faster if we'd recognized we were mistaken about the build we were running.

Ugly but short proof of concept for generating meta-data at build time:

```
echo `git remote -v | egrep origin.*fetch | sed s/origin// | sed "s/https:\/\/github.com\///" | sed "s/.git (fetch)//"` `git branch | egrep "\*" | sed "s/\* //"` `date`
```
