### ISSUE TITLE
Need a network level test for a client securely transacting with multiple peers

### ISSUE THREAD

**Issue by angrbrd** [hyperledger-archives/fabric#2004]
## Description

This issue is being opened as a result of discussion here: https://github.com/hyperledger/fabric/issues/1991

The issue is that the enrollmentID and enrollmentSecret pair that is used to perform the enrollment with the membership service server is a one-time-use set of credentials. Once you have performed the enrollment one time on one peer, it will fail on subsequent enrollments. If the client must send their transaction to one of the other peer IP addresses, not the original peer IP that performed the user enrollment, that second peer will not have the appropriate user cert/tokens to transact. The current approach to transacting through multiple peers was to configure the application and peer nodes to replicate the location of the stored crypto materials among themselves. 

We need a network level Behave test to verify the functionality above. @jeffgarratt please advice.
## Describe How to Reproduce

If you log in through either the CLI or the REST API into one of the peer nodes, you will not be able to enroll through the same credentials on another peer. You will receive an error: "Identity or token does not match". That is expected, but the approach to replicate the crypto tokens between peers must be tested. It has been described, but not demonstrated/tested through Behave in our environment.

**Comment by mastersingh24** [comment]
We should never replicate credentials across peers.  I don't think the use case is valid in real life because if multiple entities are hosting peers (which is how a blockchain should be deployed), then certainly you don't want the credentials for a user/client from one entity replicated to another entity's peer.

I also don't think that we should spend a whole lot of time at this point on the current REST implementation.  The right way to do this is going to be to go with managed / smart clients / wallets which might choose to expose the REST API.  I would have mentioned setting up the NVP as a "proxy" and adding the ability to specify the target peer, but NVPs as they exist today are not the strategic approach.

Note:  With the new NodeJS SDK people can build apps which can use the same credentials to speak to multiple peers and that is the way to handle this in the short term

**Comment by angrbrd** [comment]
@mastersingh24 thanks for this. I have also discussed with @jeffgarratt. We think you bring up a good point about the validity of the use case and more so, the fact that the current REST implementation will not be supported for much longer. I will go ahead and close for now. If that may change, we can always reopen.

Thanks.
