### ISSUE TITLE
Bug fixes - Upgrade fabric (Phase 1)

### ISSUE THREAD

**Issue by ibmmark** [hyperledger-archives/fabric#2106]
Upgrade to new level of fabric that will not cause changes in protocol so no worry about backward compatibility issues. Simply bug fixes that take down the node and replace.
This is to track the phases of applying fixes to fabric components.

Phase 1 - Take node down and replace. Simple bug fixes 
Phase 2 - Changes that create protocol compatibility issues. Require migration path

**Comment by christo4ferris** [comment]
@ibmmark I gather that this is an epic? Unclear what the child stories are since GH doesn't do epics very well (at all). Is the intent to drive to a live-upgrade capability for a network's nodes? 

"As an operator, I would be able to deploy an upgraded/patched image of the [component] across my network of fabric [components] without impacting the overall operations of the network itself."

I am not sure I would describe as two phases... I think it is more likely that for a breaking change, it is required that a live migration be specified and thoroughly/exhaustively tested before it is merged.

**Comment by ibmmark** [comment]
Closing this, moved to Epic in Jira [FAB-53](https://jira.hyperledger.org/browse/FAB-53?filter=-2)
