### ISSUE TITLE
Dealing with errors when executing a block of transactions

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#215]
We're not doing error handling now, but we will be very soon and this affects the message structures I'm designing for PBFT.
1. What are the possible error values one might get in that `errors` array when running `ExecTXs()`? Can we enumerate them?
2. True or false: Consider a block of 3 transactions. Transaction #2 returns an error, but the rest of the transactions execute fine and a candidate global state hash is generated. The consensus round should proceed normally for that block of transactions. (According to what @binhn, @muralisrini, and I discussed two weeks ago, this should be true.)

**Comment by corecode** [comment]
Right now the `PrepareResult` and `CommitResult` carry `tx_errors` and `global_hash`.  What should the PBFT plugin do with this information?  Should we add an interface to `CPI` to supply this information to the rest of the stack?

**Comment by binhn** [comment]
When we exec a batch of txs, we expect 3 returned values:
1) state hash
2) delta hashes of each tx (hash of the changed state that the tx did)
3) errors list

Resolution is as follow:
1) if errors is nil, we do consensus as normal. If errors not nil, we assume that the chaincode delta state has been rolled back by the chaincode exec (@muralisrini  please confirm), so we will do consensus as normal and record all txs and their correspondent errors on the ledger ( @manish-sethi please confirm)
2)  If can't agree due to inconsistent state hash, broadcast the delta hashes and look for which txs are inconsistent. Pull those out and mark them as inconsistent and quarantine them (should fire events when event hub is implemented);  roll back the batch or all txs starting with the first inconsistent tx;  ( @manish-sethi when we roll back a tx, would the state hash be recalculated? if not, we just roll back the block and restart without exec the inconsistent txs ). At this point, we can rerun the consensus. All txs will be recorded on the ledger
3) Need a good mechanism to eliminate the inconsistent chaincode from the system

**Comment by corecode** [comment]
Thank you for the overview.

Which part of the system should take care of execution, quarantine, and rollback?  Is this part of chaincode, or should we implement this in the PBFT plugin or in the consensus layer?

**Comment by muralisrini** [comment]
"If errors not nil, we assume that the chaincode delta state has been rolled back by the chaincode exec "

Correct. There's a TODO in chaincode.Execute(...) call for rolling back a transaction on failure. I was not sure if the call is is available in ledger. @manish-sethi : if there's one can you let me know please ?

**Comment by manish-sethi** [comment]
@muralisrini In the present form, ledger works at the level of a batch. The entire batch can either be committed (commits the state changes caused by entire batch) or rolledback (rolls back the state changes caused by entire batch). 
Rolling back a single tx is not available in ledger. In fact, ledger does not even know which tx within the batch is modifying which part of the state. 
In order to implement this , we will need to mark begin/end of a tx in the ledger (say - have new methods beginTx(protos.Transaction) and endTx(rollback bool). Also, it will be assumed here that the rollback will be called before calling beginTx(protos.Transaction) for the next Tx in the batch.

@binhn 
A - "2) delta hashes of each tx (hash of the changed state that the tx did)" 
- This is not there (see the above description - Ledger is not even aware which tx with in a batch is making changes)

B - "so we will do consensus as normal and record all txs and their correspondent errors on the ledger"
- []protos.Transaction is what is passed to CommitTxBatch method. So if protos.Transaction contains error field (@muralisrini is this how you plan to pass errors related a transaction execution) it will be stored in the block.

C - "when we roll back a tx, would the state hash be recalculated?"
Short answer is yes. Because as of now, we are applying optimization assuming the state hash is computed for a given batch of changes. Otherwise, if have to support rolling back to a certain point back in the batch - either we have to sacrifice batch-level optimization and recalculate state hash after each Tx execution (and keep track of this) or recompute by applying state changes up to first inconsistent tx.
 The former may not be good because, it will cause performance penalties in the normal execution path to handle rollbacks later (which would be rare, I suppose).  
So, as @binhn suggested, we either rollback the entire batch and reconstruct batch (by execluding 'non-deterministic' Txs) - Or we can recompute the state hash by considering changes made just before first 'non-deterministic' tx (if you think that it is worth saving re-executing chain codes).

**Comment by binhn** [comment]
@manish-sethi  @muralisrini  Thanks for the input. I think we should optimize the majority case (batch-level) and handle the exception case as necessary.  However, that means we still need the ability to say "forget the changes that a tx has just made because we got error".  On the other hand, we can roll back the entire batch if we can't agree on the result, but in this case we need the delta hash of the tx recorded as part of the returned value in order for us to figure out the inconsistent txs.  I think that's the basic capability we need to support in order for us to provide immediate finality.

**Comment by markparz** [comment]
change to Milestone 4

**Comment by kchristidis** [comment]
An example is needed here to make sure we're all on the same page.

Assume a batch of 3 transactions: `[0] [1] [2]`.
Assume that the second transaction is giving an error.

Do further assumptions for the hashes (global, delta) that each transaction generates, and list them here.

What is the flow that you all expect?

**Comment by binhn** [comment]
@kchristidis  An error as said above would be handled like this:  
- run tx0
- run tx1; roll back tx1
- run tx2
  At this point we should be able to do consensus.

Assume further that tx0 were inconsistent and updated its state differently on each VP. The returned would be:
- state-hash = 12345
- errors = [nil, error, nil]
- delta-hashes = [12321, nil, 23421]  
  < note that on other VPs, delta-hashes[0] != 12321 and state-hash != 12345 >

In this case, since we can't consent, we have to roll back the entire batch and find the inconsistent txs, and we would find tx0 and quarantine its chaincode.

For the flow, given that we exec-transactions upon receiving the batch, I thought we could do inline as part of PREPARE(state-hash, delta-hashes) then COMMIT(state-hash, delta-hashes, bad-txs)

**Comment by kchristidis** [comment]
Closed for now as we're doing classic PBFT.
