### ISSUE TITLE
Consensus should persist prepare/commit certificates for auditing

### ISSUE THREAD

**Issue by corecode** [hyperledger-archives/fabric#221]

**Comment by kchristidis** [comment]
@manish-sethi let's talk a bit about this.

I'm drawing out the data structures needed for this (see #168), and I _think_ it boils down to two maps (`reqLog`, `commitLog`), which look roughly like this:

```
type index struct {
    view string
    seq unit64
}

type certificate struct {
    prePrepare *PrePrepare
    prepares []*Prepare
    commits []*Commit
    newGlobalHash []byte
}

reqLog map[string]*Request
certLog map[index]*certificate
```

We would need to persist these two maps periodically.

Two questions off the top of my head:
1. Is there anything we need to keep in mind when persisting maps to RocksDB?
2. Will you be able to key `commitLog` by the `newGlobalHash` field once persisted?

**Comment by manish-sethi** [comment]
@kchristidis 
1) What you need to consider is that what is the nature of evolution of the map and how you want to group the data in DB for efficient retrieval.
- If there is a clear event in your code on which you want to remove a bunch of entries from your maps and persist them, it should be straight to implement. After persisting, during look-up, you first look in map, if not found then go to db.
- How to map the entries to db key-values - One straight forward way could be to have a simple one-to-one mapping i.e., one key-value in db per map entry. However, this may want to think on some other mapping if you know the access pattern in advance. For instance, if you know that a group of entries needs to be made available all together then you may like to group them differently.

2) if there's going to be one `certLog` given a `newGlobalHash`, it is easy. Otherwise, some manipulation would be required in the keys/values.

**Comment by kchristidis** [comment]
@manish-sethi thank you for the quick reply.

Follow-up comments:
1. We'll be persisting periodically (say, every 10,000 certLogs), and we will not have to retrieve this persisted data from the DB. (That's something that the auditor may want to do.)
2. One `certLog` per `newGlobalHash` so it looks like we're good.

I'll finalize the data structures by the end of the week, and we'll talk again then about an API from the `db` package that will allow us to persist our data.

**Comment by binhn** [comment]
related: #69

**Comment by binhn** [comment]
@kchristidis I'd like to discuss the reasons why the data structs and 2 logs. Once that's understood, we then can update the description with more clarity

**Comment by kchristidis** [comment]
@binhn noted; I'll draw it out on the whiteboard tomorrow and we can figure out if any changes are necessary.

**Comment by vukolic** [comment]
@kchristidis @binhn We may want to redesign auditability of consensus to reduce the number of signatures - which impacts this issue. We should try to discuss this asap.

**Comment by kchristidis** [comment]
Closed, based on the discussion we had yesterday.

**Comment by kchristidis** [comment]
We'll go without signatures in the `PREPARE` and `COMMIT` messages.

According to the slides that @vukolic and Christian shared,  this means that we need to query at least `f+1` validators to audit the ledger.
