### ISSUE TITLE
Enhancements to CPI

### ISSUE THREAD

**Issue by corecode** [hyperledger-archives/fabric#223]
For reference:

``` go
type Consenter interface {
    RecvMsg(msg *pb.OpenchainMessage) error
}

type CPI interface {
    SetConsenter(c Consenter)
    HandleMsg(msg *pb.OpenchainMessage) error
    Broadcast(msgPayload []byte) error
    ExecTXs(ctx context.Context, txs []*pb.Transaction) ([]byte, []error)
    Unicast(msgPayload []byte, receiver string) error
}
```
1. messages into the plugin and out of the plugin do not conform to the same format:  in comes `OpenchainMessage`, out goes `[]byte`
2. `RecvMsg` is used to duplex both `OpenchainMessage_REQUEST` and `_CONSENSUS`
3. `CPI` defines an interface for both the plugin to use (`Broadcast`, `ExecTXs`, `Unicast`), and for the rest of the stack (`SetConsenter`, `HandleMsg`)
4. `ExecTXs` takes a `context.Context`: where does this come from, why does the plugin care about the context?

**Comment by corecode** [comment]
My proposal:
- **(1)**, **(2)**, **(4)**:
  - handle OpenchainMessage unpacking in consensus/helper
  - have the helper broadcast the request to all peers (this is independent of the consensus protocol; all peers need the transactions)
  - add a `Request` method to the `Consenter` interface.  helper hands in a digest of the `TransactionBlock` as reference; `ExecTXs` takes this digest and executes the transaction once consensus is reached
- **(3)**: split `CPI` into a plugin-facing interface (`Broadcast`, `Unicast`, `ExecTXs`), and, if needed a stack-facing interface (`SetConsenter`, `HandleMsg`)

**Comment by kchristidis** [comment]
A few comments here:

RE: 1+2. This is a conscious design decision. You get an `OpenchainMessage` and just because its type can be either `request` or `consensus`, you let the plugin figure out how to deal with it.

On the other hand, what is broadcasted out of the consensus layer should always be an `OpenchainMessage` of type `consensus`. Thus we ask that the peer only provides us with the payload of that message. I don't see why we need to have the same type of input and output. We _can_ (it's a matter of changing a few lines), but the case for _why_ has not been made.

I am also not sure that a request should always be broadcast to all peers. Doesn't this depend on the algorithm? Esp. in the case of a scheme that deals with private transactions, you may want to avoid broadcasting to all? These are questions. Unless you can say with certainty that the answer is "no" to both, then your suggestion of having the helper do the broadcast may not be the way to go. (And that'll force us to have the plugin deal with both `request` and `consensus` which.... brings us to the design that we currently have in place.) @binhn feel free to chime in here.

RE: 3. That's a good call. Can you submit a pull request that splits CPI as you suggest?

RE: 4. I have the same question, which is why I've asked @muralisrini to write a unit test for this function -- I want to see it in action. See #214.

**Comment by corecode** [comment]
A symmetrical API interface is just more elegant.

Modified proposal:
- **(1)**, **(2)**, **(4)**:
  - handle OpenchainMessage unpacking in consensus/helper
  - add a `Request` method to the `Consenter` interface.  helper hands in an opaque transaction payload (which may contain a `TransactionBlock` - up to the stack); `ExecTXs` takes this transaction payload and executes the transaction once consensus is reached.
  - the PBFT instance receiving the `Request` call then broadcasts the request.
- **(3)**: split `CPI` into a plugin-facing interface (`Broadcast`, `Unicast`, `ExecTXs`), and, if needed a stack-facing interface (`SetConsenter`, `HandleMsg`)

I can create a pull request that will sketch my proposed API changes.

**Comment by kchristidis** [comment]
I'm noting the comment on the assymetry of the `RecvMsg()`/`Broadcast()` call. For now, let's keep it as is cause it's useful and it takes care of the packing for us. If we get everything else done, we can revisit it and take care of it.

As for your modified proposal:
- When you write "handle OpenchainMessage unpacking in consensus/helper" what do you mean? What does the helper do specifically? Remember what I said -- it may _not_ be a given that we always broadcast a `request`. We should leave this decision to the plugin.
- I'm also not sure why we need `Request()` on a `Consenter`? Can you explain what's the gap it's filling?

**Comment by corecode** [comment]
I'll provide some source tomorrow to illustrate what I mean.

**Comment by kchristidis** [comment]
That'll be great, thanks!

**Comment by binhn** [comment]
@kchristidis as I mentioned to you on slack, the interface for the plugin is changing due to integration with Jeff's new work for broadcast, so I would suggest hold off on this work and focus on the algo implementation, which @corecode  MUST execute the tx's prior to PREPARE

**Comment by corecode** [comment]
related to your comment, yet not to this issue: #226

**Comment by corecode** [comment]
PR in #229
