### ISSUE TITLE
Gerrit requires new ReadTheDocs build process

### ISSUE THREAD

**Issue by joshhus** [hyperledger-archives/fabric#2347]
## Description

GitHub build process now legacy. Need new Gerrit build process for Read The Docs
## Describe How to Reproduce

Obsolete message: https://github.com/hyperledger/fabric
Obsolete build: http://hyperledger-fabric.readthedocs.io/en/latest/
New target output: http://gerritlib.readthedocs.io/en/latest/

**Comment by joshhus** [comment]
@rameshthoomu fyi ...

**Comment by rameshthoomu** [comment]
@joshhus : looking into this..Will give you an update soon..

**Comment by joshhus** [comment]
GitHub will not be rebuilt moving fwd, correct? We'll have to build our ReadTheDocs output directly from Gerrit moving forward, is that definitivie yet. ... (Gerrit is not supported by the RTD process that we used for GitHub. We'd need a new process to go from Gerrit .md to RTD/HTML display.) @christo4ferris @ibmmark @nickgaski @rameshthoomu

**Comment by ghaskins** [comment]
Someone posted this recently: http://docs.openstack.org/infra/manual/developers.html

An interesting attribute of that system is that Gerrit is not the end-all-be-all repository, but rather it is the gateway to the repository which is hosted outside of gerrit.  I am wondering if perhaps we want to adopt something similar: for instance, the output of the gerrit/jenkins process could be a push to github.

If that were to be the case, would any of these peripheral casualties such as readthedocs be easily solved?

**Comment by rameshthoomu** [comment]
Generated mkdocs documentation for few pages using ReadTheDocs theme. Below are the steps followed:

```
pip install mkdocs
mkdocs new my-project
cd my-project
modify mkdocs.yaml file with relevant .md files
mkdocs serve - //mkdcos comes with a built-in server and runs in 127.0.0.1:8000 
mkdocs build --clean // Builds documentation  with mkdocs.yaml configuration
scp -r ./site usr@host:/path/to/server/root -- Copy site directory to hosting server
```

Reference document.  
![capture](https://cloud.githubusercontent.com/assets/17034502/17416783/d9d50448-5a5d-11e6-9f93-8f0c8c68e291.PNG)

Observed couple of issues:
1. Scroll bar is not appearing
2. Unable to setup a page for each folder like in http://hyperledger-fabric.readthedocs.io/en/latest/
3. Haven't tested this in Jenkins setup. But we can do this set up in Jenkins merge job. `mkdocs build` has to run in every merge job.
4. Required domain name to publish generated document. @joshhus or @nickgaski any inputs on this?
5. Have to validate existing markdown files.

Below is the reference link on Deploying site directory to other providers:
http://www.mkdocs.org/user-guide/deploying-your-docs/#other-providers
Working on above issues..

**Comment by rameshthoomu** [comment]
I have followed above build process in jenkins and pushed html documents to Soft layer Machine ( For Testing). Below is the url for reference. Fixed all the above issues..

 http://169.53.62.117/site/index.html

We need storage location to store these documents and domain name has to set for the new link.

**Comment by nickgaski** [comment]
@hyperledger/fabric-maintainers @cbf 

This new process that Ramesh has set up provides a remedy for all the known issues - i.e. works with Gerrit and no search headaches.  We just need to clarify what we want the **new domain name** to be.  It's currently running the Jenkins build on a Soft Layer machine...  I think we can leave it there unless there are objections.

**Comment by cbf** [comment]
i have no idea why i get these emails!

**Comment by nickgaski** [comment]
Sorry @cbf , I was looking for @christo4ferris !!!

**Comment by rameshthoomu** [comment]
@nickgaski @christo4ferris : Below is the summary of mkdocs build process: 
Building project documentation using [mkdocs](http://www.mkdocs.org/) and built-in [readthedocs](http://www.mkdocs.org/user-guide/styling-your-docs/#readthedocs) themes. Below is the process following so far.. (no more readthedocs)

Execute `mkdocs build --clean` command from the Jenkins test machine (not LF Jenkins) after `clone gerrit fabric directory` into Jenkins work space then deploy `site` directory to `Soft Layer Machine` [documentation](http://169.53.62.117/site/) If build executes successfully without Error. 

We can keep this documentation in Soft Layer machine but required "domain name" setup for the above IP address. Otherwise, we should have a hosting web server with valid domain name running in it.

**Comment by christo4ferris** [comment]
I think that the LF can host on the server (or cloud) that hosts hyperledger.org. Ry?
 
Cheers,Christopher FerrisIBM Distinguished Engineer, CTO Open TechnologyIBM Cloud, Open Technologiesemail: chrisfer@us.ibm.comtwitter: @christo4ferrisblog: https://developer.ibm.com/opentech/author/chrisfer/phone: +1 508 667 0402
 
 
----- Original message -----From: Ramesh Babu notifications@github.comTo: hyperledger/fabric fabric@noreply.github.comCc: Christopher B Ferris/Waltham/IBM@IBMUS, Mention mention@noreply.github.comSubject: Re: [hyperledger/fabric] Gerrit requires new ReadTheDocs build process (#2347)Date: Tue, Aug 9, 2016 10:51 AM 
@nickgaski @christo4ferris : Below is the summary of mkdocs build process:Building project documentation using mkdocs and built-in readthedocs themes. Below is the process following so far.. (no more readthedocs)
Execute mkdocs build --clean command from the Jenkins test machine (not LF Jenkins) after clone gerrit fabric directory into Jenkins work space then deploy site directory to Soft Layer Machine documentation If build executes successfully without Error.
We can keep this documentation in Soft Layer machine but required "domain name" setup for the above IP address. Otherwise, we should have a hosting web server with valid domain name running in it.

**Comment by christo4ferris** [comment]
I would need to talk to Core IT at LF to see how we handle that. I'm sure
something can be worked out.

**Comment by joshhus** [comment]
If we can pick and choose our URL ... since we were at http://hyperledger-fabric.readthedocs.io ... I would suggest www.hyperledger-fabric.io ... or similar per LF ... io = "input / output" = a new trendy domain extension for tech startups etc. Hopefully we can also route the old to the new automatically.

**Comment by christo4ferris** [comment]
https://jira.hyperledger.org/browse/FAB-210 closing
