### ISSUE TITLE
start container with HostConfig was deprecated since v1.10 and removed in v1.12

### ISSUE THREAD

**Issue by xiejunan** [hyperledger-archives/fabric#2365]
I can not deploy chaincode to docker v1.12 successfully because HostConfig being passed to client.StartContainer. I see Baohua's comment but i suggest pass a nil to StartContainer because HostConfig has   been passed to  vm.createContainer already. 
ref: core/container/dockercontroller/dockercontroller.go

**Comment by yeasy** [comment]
OK, will fix that.

**Comment by JonathanLevi** [comment]
@2016Nishi, FYI

**Comment by cophey** [comment]
marked.The same error.

> [dockercontroller] Start -> ERRO 01e start-could not start container API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

**Comment by VenkyMadgundi** [comment]
I am also getting same error:
[dockercontroller] Start -> ERRO 019 start-could not start container API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
[chaincode] Launch -> ERRO 01a launchAndWaitForRegister failed Error starting container: API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

**Comment by muralisrini** [comment]
@VenkyMadgundi the project has moved to gerrit. This has been fixed there

![image](https://cloud.githubusercontent.com/assets/14361488/17837364/692d4154-677f-11e6-8fdc-49639d03fcc1.png)

**Comment by christo4ferris** [comment]
closing per @muralisrini comment above.
