### ISSUE TITLE
Implement trie based Merkel tree implementation for state management

### ISSUE THREAD

**Issue by manish-sethi** [hyperledger-archives/fabric#243]
This issue is a break-up of #41 
Implement trie based merkel tree (as per #242 ) for computing crypto-hash of world-state.

**Comment by corecode** [comment]
Does this also address (efficiently) synchronizing world state between peers?

**Comment by srderson** [comment]
This issue is for the hash calculation.

For syncing state between peers, in Ledger.go there is 'GetStateSnapshot`and`GetStateDelta`, but these are not being called yet. I think part of this work would be completed in issue https://github.com/openblockchain/obc-peer/issues/145. I'm not sure if we have an existing issue for a peer detecting that it is out of sync and starting the process of asking for and downloading the state from another peer.

**Comment by srderson** [comment]
Adding sprint 4. The current default state storage implementation is issue #244

**Comment by srderson** [comment]
@manish-sethi Closing as I believe this is complete now.
