### ISSUE TITLE
Support for security related client queries

### ISSUE THREAD

**Issue by manish-sethi** [hyperledger-archives/fabric#246]
This is an issue created out of #73 for tracking the remaining queries once the security related information is available in relevant proto messages.
Get transaction by address
Get transaction by identity
Get chaincodes an address have access to

**Comment by binhn** [comment]
@manish-sethi it looks like we can't do "get transaction by identity" since the identity is not "linkable" to the transactions. It would require the security entity and proper authority to link transactions to the user id.  We can do "get transactions by tcert-public-key". 

I would break this issue into 2 issues: 1 we can do without security integration and 1 would require security integration, which is be likely during sprint 2

**Comment by manish-sethi** [comment]
@binhn sure. This makes sense. 
However, just curious that will it be useful to expose "get transactions by tcert-public-key"?
Marking @srderson, as he had compiled the original list of queries.
