### ISSUE TITLE
Network of VPs and NVPs

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#284]
Set up and test a network of VPs and NVPs with 2 chaincodes

**Comment by binhn** [comment]
@jeffgarratt @muralisrini  Would this work today? Jeff, you mentioned we need to differentiate NVP from VP in the discovery protocol, and I am not sure if you've implemented that yet

**Comment by binhn** [comment]
@muralisrini tested today and it didn't work. He'll create a defect

**Comment by muralisrini** [comment]
There are two issues (1) differentiating NVP from VP and (2) setting peer address when sending HELLO to a VP from NVP. I created bug issue #300 for the later. When working around (2), things appeared to work as expected when there was just 1 NVP in the environment. When CLI sent request to that NVP, it correctly forwarded to its VP, who broadcast to other VPs. All VPs executed the transaction. So that was all good.

I didn't focus on multiple NVP scenarios too much. In particular a key aspect of @binhn comment "we need to differentiate NVP from VP" - if I understood it correctly -  is that we'd expect VPs to not broadcast message to NVPs.

**Comment by binhn** [comment]
@muralisrini @jeffgarratt  It looks like we need to move this to sprint 2 or 3 if we are using sec ID as a differentiator for VP vs NVP.  I would prefer some other mechanism in the meantime to help us test the network.

**Comment by binhn** [comment]
per scrum today as this is pending security integration

**Comment by binhn** [comment]
move to sprint 4 pending security integration

**Comment by binhn** [comment]
Since this is a non-dev item, move to testing cycle
