### ISSUE TITLE
User interface design for monitor

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#294]
Related #80

**Comment by seanbarclay** [comment]
FYI- after you add her to the repo, please to assign this to Andrea (@Andreayurei) next Monday.

Also, @binhn please create the following tag groups with sub tags: 
Design: UI, UX, MotionGraphics 
Front-End: CSS, JS

Thanks

**Comment by seanbarclay** [comment]
Posted to slack channel yesterday. Reviewing internally today during testnet call. Will revise based on feedback. 
![monitoring_wire_v1-03](https://cloud.githubusercontent.com/assets/181646/11536246/6042fef8-98cc-11e5-82ce-cab159f4e6f0.jpg)

**Comment by srderson** [comment]
Looks good!

Any plans to expose block information such as transactions per block, time between blocks, current block number, etc?

What is the average latency statistic?

**Comment by seanbarclay** [comment]
Feedback
- Remove Avg. Latency
- Update "Avg. Capacity" to "Transaction Rate"
- Chaincode -> change line-chart to list of top 5 chain codes (cc's)
- Network Health
  - Remove IP address column
  - Remove NVP's for time being
  - Add Location Map (@mrshah-at-ibm will research options. e.g. leafletjs.com or Mapbox)

Next Steps
- API's -> @angrbrd, @binhn and @mrshah-at-ibm will talk offline and resolve
- UI will be updated today and posted on Thursday for review
- I will package icons, fonts, and styles for @mrshah-at-ibm on Thursday

**Comment by seanbarclay** [comment]
Updated Monitor UI based on Feedback

![monitoring_wire-v1-04](https://cloud.githubusercontent.com/assets/181646/11552382/d6039b5e-9938-11e5-9fc8-43fe3c340400.png)

**Comment by muralisrini** [comment]
@seanbarclay : the autorefresh suggests a polling model ? If we implement #32 would we consider event driven model ?

**Comment by seanbarclay** [comment]
@muralisrini for starters, a polling model is the way to go. Later on, when #32 is implemented, we can revisit. 

@binhn @markparz, unless there is anything else to address, please close this ticket.

**Comment by kchristidis** [comment]
I'm looking at [the updated monitor UI](https://github.com/openblockchain/obc-peer/issues/294#issuecomment-161515699) (which is a good improvement over [this one](https://github.com/openblockchain/obc-peer/issues/294#issuecomment-161348979); couldn't figure out how to parse that "Chaincode" graph on the top).

Looks pretty nice. Here's a couple of thoughts:
1. How is consensus success defined? (I know how it _can_ be defined, I'd just like to know what the expectation, or the definition that you have in mind, is here.)
2. If you have the "Range" dropdown on the top, do you need the time dropdown (that currently reads: "Min") on the "Volume" graph? I'm a bit confused here. When I click on "Min" on that Volume graph I expect a breakdown of the volume minute-by-minute, but what is the range of the x-axis supposed to be? My immediate thought was that it should be 5 minutes as defined in the top "Range" dropdown. But what if I choose the "Hour" option on that Volume graph? How does this mix with the "Range" option when that one is set to (5) minutes. I am not sure.

**Comment by angrbrd** [comment]
Hi @kchristidis ,

For 1, please see #359 .

For 2, that is a good question. From what we discussed with @seanbarclay and @mrshah-at-ibm , it seemed to me that the range mainly pertains to the performance metric (far left) and chaincode volume (middle), not the total transaction volume (right). But I could be wrong on that... and given that it causes confusion, I agree that we should make sure we are all on the same page. Also, please keep in mind that we are still working on solidifying details and are likely to settle on discrete time windows rather than user defined windows, which would limit the drop down options that you get for either drop down (top or right). Meaning, instated of being able to select any range you want, you would be limited to options such ranges of last 1min, 5min, 10min, 30min, 1hr. At this time computing user defined queries is not necessary.

Thanks.

**Comment by seanbarclay** [comment]
IMHO we can remove the range for now.

**Comment by angrbrd** [comment]
Hi @seanbarclay ,

I discussed with @binhn and @srderson yesterday on the statistics we will be computing and exposing through the APIs for you to display. @binhn and @srderson please correct if what I say below is not accurate.

For the time being, we have settled on representing _only_ the last 15 minute segment of network activity. Therefore, we will be returning the transaction rate (per second) as the total number of transactions averaged over the last 900 seconds. That being said, please remove the range control from the top, as we will not be currently using that. Similarly for transaction volume, we will be returning the total number of transactions for the past 15 minutes displayed in intervals of 1 min. Please remove the range/scale control from the volume graph as well.

Thanks!

**Comment by seanbarclay** [comment]
Thanks @angrbrd. Updated UI below. IF good please close issue. Thanks!

![monitoring_wire-v1-05](https://cloud.githubusercontent.com/assets/181646/11847938/a76534dc-a3d4-11e5-9e9d-699e2d95ef32.png)

**Comment by seanbarclay** [comment]
FYI, slight typeface modification to match updated website UI.

**Comment by angrbrd** [comment]
@seanbarclay , this looks good to me per my earlier comment. Closing issue.

Thanks.

**Comment by buhrmi** [comment]
Just a quick question. Where is the web ui implemented? Does an implementation exist? Or is it only a design?

**Comment by srderson** [comment]
@buhrmi The above images are a design, but an open source web ui has been started at https://github.com/konradpabjan/fabric/tree/master/peer/Explorer. I saw it for the first time today and it looked like a great start. I think @konradpabjan may discuss it more at the TSC call this Thursday.

**Comment by dshuffma-ibm** [comment]
ah, I don't want to step on anyone toes, but...  We have converted the UI we have for the IBM Blockchain service on Bluemix to a standalone node.js app.  A user can start up our app, type in some configuration information about your network and get a UI that looks pretty similar to the Bluemix version. It is not ready for public release, but its not too far off.

We basically stripped out any features that are dependent on our infrastructure so that it would work with any instance of Hyperledger at the REST interface level. I'll bookmark this issue and update it when its ready for initial release.

Of course this version could just be one of many different UIs that are available! =)

**Comment by srderson** [comment]
@dshuffma-ibm yup, no issues having multiple implementations, especially early on. By "public release" do you mean that you want to donate the code to Hyperledger, meaning it will live in the Hyperledger organization?

**Comment by christo4ferris** [comment]
@dshuffma-ibm what @srderson said... we discussed on the Hyperledger TSC today and everyone seemed in general agreement to having an 'explorer' project. We could have multiples that we sought to consolidate through the incubation. I think that Intel also has one (in addition to the DTCC one).

**Comment by dshuffma-ibm** [comment]
ten four.  also our plan is to open source the UI.  Hyperledger / anyone could absorb it or components of it as they please.
