### ISSUE TITLE
devops chats need to send peer address on HELLO

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#300]
in non-Validator mode, the chat initiates a regular "HELLO" message in peer.SendTransactionsToPeer. This would need to send peer address just as other Chat initiations do (example, chat initiation in NewPeerHandler). 

@jeffgarratt :  Not sure if duplicating marshal-peer-address-and-send whereever we send HELLO is the right way to do this.... assigning it to you if you are already looking to clean up this area (related issue #256)

**Comment by binhn** [comment]
We have a fix for this issue, but currently I see another error in the log though things seem to work fine. Error marked with ### below:

15:04:51.598 [peer] GetPeerEndpoint -> WARN 035 AutoDetected Peer address: 172.17.0.3:30303
15:04:56.404 [devops] Build -> DEBU 036 Received build request for chaincode spec: type:GOLANG chaincodeID:<url:"github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02" version:"0.0.1" > ctorMsg:<function:"init" args:"a" args:"100" args:"b" args:"200" > 
15:04:56.404 [devops] checkSpec -> DEBU 037 Validated spec:  type:GOLANG chaincodeID:<url:"github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02" version:"0.0.1" > ctorMsg:<function:"init" args:"a" args:"100" args:"b" args:"200" > 
15:04:56.404 [container] NewVM -> INFO 038 Creating VM with endpoint: http://172.17.0.1:4243
15:04:56.404 [container] writeGopathSrc -> INFO 039 rootDirectory = /go/src
15:04:56.592 [consensus/helper] HandleMessage -> DEBU 03a Did not handle message of type DISC_GET_PEERS, passing on to next MessageHandler
15:04:56.593 [peer] HandleMessage -> DEBU 03b Handling OpenchainMessage of type: DISC_GET_PEERS 
15:04:56.593 [peer] beforeGetPeers -> DEBU 03c Sending back DISC_PEERS
15:04:56.598 [consensus/helper] HandleMessage -> DEBU 03d Did not handle message of type DISC_PEERS, passing on to next MessageHandler
15:04:56.598 [peer] HandleMessage -> DEBU 03e Handling OpenchainMessage of type: DISC_PEERS 
15:04:56.598 [peer] beforePeers -> DEBU 03f Received DISC_PEERS, grabbing peers message
15:04:56.598 [peer] beforePeers -> DEBU 040 Received PeersMessage with Peers: peers:<ID:<name:"vp2" > address:"172.17.0.3:30303" > 
15:04:56.599 [peer] GetPeerEndpoint -> WARN 041 AutoDetected Peer address: 172.17.0.3:30303
15:04:56.960 [container] GetVMName -> DEBU 042 return VM name: dev-vp2-github.com.openblockchain.obc-peer.openchain.example.chaincode.chaincode_example02:0.0.1
15:05:01.592 [consensus/helper] HandleMessage -> DEBU 043 Did not handle message of type DISC_GET_PEERS, passing on to next MessageHandler
15:05:01.592 [peer] HandleMessage -> DEBU 044 Handling OpenchainMessage of type: DISC_GET_PEERS 
15:05:01.593 [peer] beforeGetPeers -> DEBU 045 Sending back DISC_PEERS
15:05:01.599 [consensus/helper] HandleMessage -> DEBU 046 Did not handle message of type DISC_PEERS, passing on to next MessageHandler
15:05:01.599 [peer] HandleMessage -> DEBU 047 Handling OpenchainMessage of type: DISC_PEERS 
15:05:01.599 [peer] beforePeers -> DEBU 048 Received DISC_PEERS, grabbing peers message
15:05:01.599 [peer] beforePeers -> DEBU 049 Received PeersMessage with Peers: peers:<ID:<name:"vp2" > address:"172.17.0.3:30303" > 
15:05:01.600 [peer] GetPeerEndpoint -> WARN 04a AutoDetected Peer address: 172.17.0.3:30303
15:05:06.193 [devops] Deploy -> DEBU 04b Sending deploy transaction (b43a1542-d30c-48cd-a0d8-71891f592a1a) to validator
15:05:06.196 [peer] SendTransactionsToPeer -> DEBU 04c Sending HELLO to Peer: 172.17.0.2:30303
15:05:06.198 [peer] GetPeerEndpoint -> WARN 04d AutoDetected Peer address: 172.17.0.3:30303
15:05:06.200 [peer] func1 -> DEBU 04e Received DISC_HELLO message as expected, sending transaction...
15:05:06.257 [peer] func1 -> DEBU 04f Transaction sent to peer address: 172.17.0.2:30303
15:05:06.258 [peer] func1 -> DEBU 050 Got unexpected message DISC_HELLO, with bytes length = 25,  doing nothing
15:05:06.264 [peer] func1 -> DEBU 051 Received RESPONSE message as expected, exiting out of receive loop
15:05:06.407 [consensus/noops] RecvMsg -> DEBU 052 Handling OpenchainMessage of type: CONSENSUS 
15:05:06.407 [consensus/noops] RecvMsg -> DEBU 053 Handling OpenchainMessage of type: CONSENSUS 
15:05:06.410 [consensus/noops] RecvMsg -> DEBU 054 Executing transactions
15:05:06.419 [container] GetVMName -> DEBU 055 return VM name: dev-vp2-github.com.openblockchain.obc-peer.openchain.example.chaincode.chaincode_example02:0.0.1
15:05:06.419 [chaincode] DeployChaincode -> DEBU 056 Executable is /go/bin/chaincode_example02
15:05:06.422 [chaincode] DeployChaincode -> DEBU 057 deploying vmname dev-vp2-github.com.openblockchain.obc-peer.openchain.example.chaincode.chaincode_example02:0.0.1
15:05:09.142 [container] build -> DEBU 058 Created image: dev-vp2-github.com.openblockchain.obc-peer.openchain.example.chaincode.chaincode_example02:0.0.1
15:05:09.142 [container] build -> DEBU 059 Create image: dev-vp2-github.com.openblockchain.obc-peer.openchain.example.chaincode.chaincode_example02_0.0.1
15:05:09.228 [container] build -> DEBU 05a Created container: dev-vp2-github.com.openblockchain.obc-peer.openchain.example.chaincode.chaincode_example02:0.0.1
15:05:09.228 [state] txBegin -> DEBU 05b txBegin() for txUuid [b43a1542-d30c-48cd-a0d8-71891f592a1a]
15:05:09.230 [container] GetVMName -> DEBU 05c return VM name: dev-vp2-github.com.openblockchain.obc-peer.openchain.example.chaincode.chaincode_example02:0.0.1
15:05:09.349 [container] start -> DEBU 05d Started container dev-vp2-github.com.openblockchain.obc-peer.openchain.example.chaincode.chaincode_example02_0.0.1
15:05:09.381 [chaincode] HandleChaincodeStream -> DEBU 05e Current context deadline = 0001-01-01 00:00:00 +0000 UTC, ok = false
15:05:09.382 [chaincode] HandleMessage -> DEBU 05f Handling ChaincodeMessage of type: REGISTER in state created
15:05:09.382 [chaincode] beforeRegisterEvent -> DEBU 060 Received REGISTER in state created
15:05:09.382 [chaincode] registerHandler -> DEBU 061 registered handler complete for chaincode github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02:0.0.1
15:05:09.382 [chaincode] beforeRegisterEvent -> DEBU 062 Got REGISTER for chaincodeID = url:"github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02" version:"0.0.1" , sending back REGISTERED
15:05:09.385 [chaincode] notifyDuringStartup -> DEBU 063 Notifying during startup
15:05:09.385 [chaincode] notifyDuringStartup -> DEBU 064 Notified during startup
15:05:09.386 [chaincode] initOrReady -> DEBU 065 sending INIT
15:05:09.386 [chaincode] initOrReady -> DEBU 066 Failed to trigger FSM event READY : event INIT inappropriate because previous transition did not complete
15:05:09.386 [chaincode] LaunchChaincode -> DEBU 067 sending init failed(Error sending INIT: event INIT inappropriate because previous transition did not complete)
15:05:09.388 [container] GetVMName -> DEBU 068 return VM name: dev-vp2-github.com.openblockchain.obc-peer.openchain.example.chaincode.chaincode_example02:0.0.1
15:05:09.391 [chaincode] enterestablishedstate -> DEBU 069 (enterestablishedstate)Entered state; notified established
###15:05:09.429 [chaincode] processStream -> ERRO 06a Error handling chaincode support stream: connection error: desc = "transport is closing"
15:05:09.429 [chaincode] deregisterHandler -> DEBU 06b Deregistered handler with key: github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02:0.0.1
15:05:09.491 [container] stop -> DEBU 06c Stopped container dev-vp2-github.com.openblockchain.obc-peer.openchain.example.chaincode.chaincode_example02_0.0.1
15:05:09.491 [chaincode] LaunchChaincode -> DEBU 06d sending init completed
15:05:09.491 [chaincode] LaunchChaincode -> DEBU 06e LaunchChaincode complete
15:05:09.491 [state] txFinish -> DEBU 06f txFinish() for txUuid [b43a1542-d30c-48cd-a0d8-71891f592a1a], txSuccessful=[false]
15:05:09.491 [state] getHash -> DEBU 070 Recomputing state hash...
15:05:09.491 [stateHash] computeStateHash -> DEBU 071 Computing global state hash
15:05:09.491 [stateHash] computeStateHash -> DEBU 072 Adding remaining chaincode hashes from db
(noops.RecvMsg)execute transactions successfully: 46b9dd2b0ba88d13233b3feb743eeb243fcd52ea62b81b82b50c27646ed5762fd75dc4ddd8c0f200cb05019d67b592f6fc821c49479ab48640292eacb3b7c4be
15:05:09.491 [consensus/helper] HandleMessage -> DEBU 073 Did not handle message of type DISC_GET_PEERS, passing on to next MessageHandler
15:05:09.491 [peer] HandleMessage -> DEBU 074 Handling OpenchainMessage of type: DISC_GET_PEERS 
15:05:09.491 [peer] beforeGetPeers -> DEBU 075 Sending back DISC_PEERS
15:05:09.491 [consensus/helper] HandleMessage -> DEBU 076 Did not handle message of type DISC_PEERS, passing on to next MessageHandler
15:05:09.491 [peer] HandleMessage -> DEBU 077 Handling OpenchainMessage of type: DISC_PEERS 
15:05:09.491 [peer] beforePeers -> DEBU 078 Received DISC_PEERS, grabbing peers message
15:05:09.491 [peer] beforePeers -> DEBU 079 Received PeersMessage with Peers: peers:<ID:<name:"vp2" > address:"172.17.0.3:30303" > 
15:05:09.491 [peer] GetPeerEndpoint -> WARN 07a AutoDetected Peer address: 172.17.0.3:30303

**Comment by muralisrini** [comment]
Right, things like the "###15:05:09.429 [chaincode] processStream -> ERRO"  is why we may want to understand if the fix of  " marshal-peer-address-and-send" mentioned in the main comment is the right way to fix this
