### ISSUE TITLE
Handle errors in PBFT execution phase 

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#314]
There are two sources of errors:
1. Unmarshalling the request payload
2. Executing it

See [here](https://github.com/openblockchain/obc-peer/commit/69398e44b5e3c3d390618dca67e2f8bd5a1a2135#diff-a42b3de94d2ee765430f3bcf3e852aebR478) for more.

In both cases we need to figure out what value the `lastExec` field should be set to, and whether we should `return` immediately, or record the error and `continue`.

**Comment by corecode** [comment]
I would prefer to pass in/out opaque `[]byte`, instead of unmarshalling in the pbft implementation itself.  Therefore I consider unmarshalling errors to be part of the execution, and would treat both the same way (as the code does at the moment).

Because transactions (requests) are deterministic (at this point), all replicas will execute the requests in the same way.  I consider an execution error as just another result of execution.  Therefore everything is treated the same way as a successful execution would be treated.

**Comment by kchristidis** [comment]
Makes sense. I guess passing in/out opaque `[]byte` will be handled with #272.

**Comment by corecode** [comment]
shouldn't we close this?

**Comment by kchristidis** [comment]
Done.
