### ISSUE TITLE
Implement TxRate API

### ISSUE THREAD

**Issue by angrbrd** [hyperledger-archives/fabric#353]
The testnet monitor UI will display transaction rate on the network. This issue is to implement the TxRate API and REST endpoint to return the transaction rate recorded on a peer node.

TxRate(last X seconds), where X is the number of seconds leading up to the current moment.

Must walk backwards through the blockchain, starting at the head until X has passed. Count up the number of transactions and divide by the number of seconds. Maximum X is 1hr = 3600 seconds.

**Comment by binhn** [comment]
@srderson @manish-sethi Is there a better way to do this than what @angrbrd described here? I ask because I thought of the way we store the data in db might help such time-based query

**Comment by manish-sethi** [comment]
@binhn I feel that pulling out actual blocks/transactions for stats computation (e.g, simple counts in this case) may cause much larger I/O load than needed. Especially, if this API gets called very frequently in an auto-refresh web page - this may affect the disk bandwidth for on-going transactions / batch commits.

I think, we should explore maintaining time series of desired stats; in-memory for last few sampling-windows and in a db for historical data if large history is desired.

**Comment by binhn** [comment]
@manish-sethi that's a good data point since I was contemplating on whether to recommend enabling the stats/monitor service on the VPs, so we should only enable the service on NVPs in production network unless we come up with a better solution. 

For now, we should explore the "cheapest" way to achieve this.  Are the blocks kept in memory that we may just walk the list backward to count up the number of the transactions and look up their timestamp? Or we should provide some query APIs on the ledger.

**Comment by srderson** [comment]
@manish-sethi and I discussed this morning.

The blocks are not kept in memory. The cheapest option is to quickly create a stats.go file. We will call into this from the ledger every time a block is added. The stats.go module can store the info it needs in memory. The con here is that stats can only be generated from the last startup time. To avoid this con, we need to store the stats data in the DB. It can then be quickly queried every time we need a lookup.

**Comment by angrbrd** [comment]
@srderson @manish-sethi @binhn 

I agree with the above comment of creating a separate statistics service module, which may be either enabled or disabled at runtime. The statistics service would be made available at hostIP:port/statistics.

When enabled, the statistics service will run in the background and receive a callback from the ledger whenever a new block has been committed to the blockchain. At this point, the module will examine the newly available transactions in the block to make the computations it needs.

I think it is reasonable to keep a time series window at the following intervals and just return a summary/table in the response. Transaction rate per: 10 sec, 30 sec, 1 min, 10 min, 30 min, 60 min. I don't believe it is necessary to make these windows to be any more granular as we are not expecting massive transaction loads on our network. For a user viewing the UI and being able to query things like transaction rate for 1 min vs 2 minutes or 10 minutes vs. 15 minutes seems overkill to me. So I propose we settle on discrete time windows and only return those.

And I agree that this data should be written back to another database so it persists between restarts, but that's a secondary issue in order of priority.

I would appreciate any feedback on this issue as well as the other issues #354 and #355 .

Thanks.

**Comment by srderson** [comment]
yes, agree. +1 for discrete windows. Don't need custom queries, at least initially.

**Comment by binhn** [comment]
1 problem with this approach is that VP would be the only one that can serve the stats, which contradicts with what I want the monitor to live -- on the NVP -- as stated above. In a production environment, it is unlikely that http service would be enabled on VPs due to security. Applications would have to rely on NVP to provide stats, events, and so on, so we need to focus on solution that works on both NVP and VP but emphasize NVP as the recommended deployment

**Comment by angrbrd** [comment]
@binhn I don't understand why this solution would not work on a NVP. The only thing that is necessary for this to work is a callback from the ledger when a new block is being committed to the local blockchain. That happens on the NVP when it receives the block that has been broadcast. Then the processing happens on the transactions within the newly received block. Can you elaborate why you see a problem with this approach?

**Comment by srderson** [comment]
There are two paths.

For VP, the statistics module is called from ledger.CommitTxBatch. We can add the time to the block in the NewBlock.

For NVP, the statistics module can be called from ledger.PutRawBlock. This will be called during sync and the time in the block comes from the VP.

Does that work?

**Comment by manish-sethi** [comment]
@angrbrd The overall approch looks good to me. Please find below additional comments.

I think that an additional parameter that we need to consider is the size of discrete segment because these are going to be sliding windows (Since, as I understood, you want to answer queries such as - give stats for 'last' x unit of time).

For instance, for the case of the query that shows stats for last 10 seconds, we could choose discrete segment size of 10 milliseconds or 100 millisecond. However, for more courser queries, we can choose higher segment size. For example, for the query that shows stats for last 60 minutes, a segment of somewhere between 5 and 30 seconds should be OK.
This would primarily determine the accuracy of results vs amount of memory that we would require to hold the segments for the stats.

I would suggest we create a parameterized structure that would take two parameters 1) segment-size and 2) number of segments. Internally, we can create a structure that holds the stats (counts in this case) for contiguous segments ([]int along with a few additional variables in 'go' should work). In a steady-state, we would maintain number of entries equals to the 'number of segments'. 

When you analyze a new tx for updating the stats, you would need to find out which segment the tx belongs to. If the tx belongs to one of the existing segments, you would increment the corresponding counter.
If it requires to create a new segment (latest segment), you can drop the oldest segment.

When a query arrives, you would need to start scanning from the latest segment and go up to the segment that falls in the range of the query.

This should allow us to answer queries of different ranges. For example, an instance of this structure that maintains data for 60-minutes query can answer for 30-minutes as well. 

I feel, we can start with by maintaining just two instances of the above mentioned structure. 
1) segment-size = 100 ms, number of segments = 600 - This can be used for answering any query between last 1 seconds and 1 minute
2) segment-size = 5 s,  number of segments = 720 - This can be used for answering any query between last 10 minutes and 60 minutes

Memory point of view, it will be not something that we need to worry - since one segment just needs to hold a count

We can decide on these parameters values based on the accuracy desired vs memory demands later as well (and may vary be from deployment-to-deployment)

**Comment by binhn** [comment]
@angrbrd It won't work because we would not have the failure rate (rolled back blocks) -- sorry, my comment above refers to the entire stats, not just this one metric.

@srderson  I would rather relying on an event-stream adapter to capture and process this info -- seems deja vu bc I recall discussing this way back during the inception of the architecture :-)  So where @srderson  suggested to call stats.go, we should emit events on the stream, and not just on committed blocks but also on rolled back blocks, so that the stats-adapter can keep track of anything it wants.

We should discuss the relevant events on Issue #32 to support different metrics for stats, including this one. 

From the peer, we shouldn't persist any of the time-based metrics, but we should leave that to the application (adapter). @angrbrd 's comments above are all good as requirements for the stats-adapter.

@muralisrini  we have our first customer of event hub :-)

**Comment by srderson** [comment]
@binhn @muralisrini If statistics collection is separated into an adapter, do we risk loosing data if the adapter becomes disconnected or not being able to query historical data if the adapter joins late? Not sure if that's an issue or not, just considering how this would be different compared to an atomic commit to the DB with the ledger commit.

**Comment by srderson** [comment]
@binhn For tracking failure rate (assume you meant rolled back transactions, not blocks) we do have issue #328. As the block is propagated to the NVP, it would have this information. The original purpose of issue #328 was to provide a mechanism for user to understand that a transaction was received, but failed, instead of silently discarding it. Do we still want to include this information in the block given the event hub? I'll think about this more, but let me know your thoughts. Thanks.

**Comment by muralisrini** [comment]
From above discussion, there are two main approaches to stats-like data.
1. compute and store stats right at the source in VP where events happen. Users such as monitor have to just issue GET calls. No additional computation needed at the consumer side
2. do not compute stats at source in VP but stream the events directly to those interested. Up to users such as monitor to use them as they please. For instance monitor may compute time average of stats

Does that sound right ? Model 2 has some nice characteristics
- we don't have to enforce a view of stats. e.g, in this TX rate case ... if we compute and store at VP, we are binding users to fixed view of the the TX stats (sliding window rate interval)
- it generalizes well to new events. We just create a new event type, send then to the event hub and users can begin to receive them. We don't have to invent a new stats collection mechanism for the new type (to be implemented at source)

It is true that every user has to compute stats from the events and as @srderson points out all this data become transient as they are not stored at source. Each consumer would have to maintain it. Stats such as TX rate seems to more of "transient category" though ?

**Comment by srderson** [comment]
Agree with the pros. My questions is where does the adapter that collects statistics reside? My main concern is that if the connection between the adapter and event hub is broken, can the adapter pick up where it left off or does the event hub only send real time events?

**Comment by muralisrini** [comment]
It would be up to the adapter if it wants to persist date somehow.  The hub would only send real time events.

**Comment by angrbrd** [comment]
Issue #393 must be completed first before this one may be addressed.
