### ISSUE TITLE
Implement PeerAddresses API

### ISSUE THREAD

**Issue by angrbrd** [hyperledger-archives/fabric#356]
The testnet monitor UI will display the list of all participating validating nodes in the network. This issue is to create the API and REST endpoint to retrieve the list of all nodes receiving the broadcast and participating in consensus and return the list of node name and ip address pairs for all validating nodes.

**Comment by angrbrd** [comment]
Per issue #294 , one of the things that will need to be displayed on the testnet monitor UI is the list of all validating peers in the network. In working on this, I have the following questions. I would appreciate if either @binhn or @jeffgarratt can address some of these please.

(1) At this time, are we making a strong assumption that all of the validating peers will be connected to all the other validating peers? If there are network disconnections, the network topology visible to one VP will not be the same as that visible to another VP. Are we working under the assumption that this will not happen at this time?

(2) At this time, do we assume a static network of validating peers? Am I safe to simply pull the hard coded addresses of these validating peers from the openchain.yaml for this API with  config.GetStringSlice("peer.validator.replicas")? I understand this will change in the future, but is this the best thing to do right now to get this list of validators?

(3) If using config.GetStringSlice("peer.validator.replicas") is not what we want to do, the only other thing that I could see doing for this is using the GetPeers() method inside of the /openchain/peer/peer.go file. As far as I can tell, it builds the list of peers dynamically and returns this list. The issue is, I am not sure if I can get a handle to the *PeerImpl from the API layer. The peer does not call into the API layer anywhere either. I am not so sure if this would be a good idea to make the API layer access directly into the peer layer or if it makes sense.

Let me hear your thoughts. Thanks.

**Comment by binhn** [comment]
First of all, I don't think peer.validator.replicas is valid as the network is dynamic. Furthermore, the address may not be known ahead of time of starting up the VP -- like containers, so the IP is either passed in or auto-discover (if possible). 

Second, the REST service often runs on NVP; it should not be enabled on the VP in deployment due to workload, security, and so on. This is important to note on the openchain.yaml

Therefore, we need an API on NVP and VP to get the VP's IDs. I don't think we should return the IP addresses due to potential security concerns. This is not a public network, VPs might not want to be shown on the monitor with IP addresses or specific locations.

**Comment by angrbrd** [comment]
Fixed with:

PR #667 
PR #670 
PR https://github.com/openblockchain/obc-docs/pull/94
