### ISSUE TITLE
Reliable submission of a transaction to validators

### ISSUE THREAD

**Issue by vukolic** [hyperledger-archives/fabric#394]
The way I get our current design Client submits the transaction to DevOps which is basically collocated with NVP. Each client seems to have a dedicated DevOps/NVP. This NVP then submits the transaction to a fixed VP, which is supposed to send a transaction to all VPs before it enters consensus (PBFT or Sieve).

There is an issue with this in that a faulty DevOps/NVP or a faulty VP can drop transactions. Hence, we need a mechanism to reliably re-submit transactions to guarantee they enter consensus at some point. This does not seem to be an issue of consensus module (only), but rather a cross-stack issue.

**Comment by binhn** [comment]
I think the normal operation is for the client to check the tx id; if it doesn't receive the tx id, it should resubmit.

A more expensive approach is to persist the tx at the ingress and make sure the tx processed within a time period; otherwise resubmit. However, this assumes that NVP/VP doesn't fail. Probably MQ cluster app fronting the network would be more ideal.

**Comment by kchristidis** [comment]
Let's use this issue to track the client-to-NVP part of this to match what @binhn wrote above.

#796 addresses the "VP/leader-to-block" part that falls under the "consensus" domain.

**Comment by christo4ferris** [comment]
@kchristidis given the new consensus proposal, is this still relevant? can it be closed? I would note that "devops" is deprecated.

**Comment by kchristidis** [comment]
@christo4ferris I don't think the new consensus proposal explicitly addresses this either. If we're fine with the standard operating assumption (which is what @binhn wrote above, i.e. we let the application keep track of this and handle it), then we should close it. Otherwise keep open. I vote for closing it.

**Comment by christo4ferris** [comment]
ok, closing
