### ISSUE TITLE
Get state hash from ledger for checkpoints

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#402]
Needed in `pbft-core`.

@jyellick, same note as in #400 applies: feel free to modify the *CPI functions I introduced as you see fit.

**Comment by kchristidis** [comment]
Implemented in: https://github.com/kchristidis/obc-peer/commit/2268363a989a850670189c5dd25be2624cb7f085

@jyellick Let me know if we can close this, or further refinements are needed.

**Comment by jyellick** [comment]
@kchristidis Yes, I think this is safe to close.

For posterity's sake, I'd like to point out that checkpoints are actually now implemented as the BlockHash of the latest block rather than the StateHash.  This is because in order to perform state replication, we need to be able to verify the blockchain.  The latest block, which can be verified using the BlockHash, contains the current StateHash, so the function of verifying the state is accomplished as well.

**Comment by kchristidis** [comment]
Wonderful, thanks :+1:
