### ISSUE TITLE
Deploy transactions take a long time

### ISSUE THREAD

**Issue by corecode** [hyperledger-archives/fabric#452]
Compared to invoke transactions (but also in absolute terms), deploy transactions take a very long time (many seconds).

With the sieve (non-deterministic) consensus protocol, we need to execute all transactions (and wait for their result) before the protocol can move on.  However, to prevent against a malicious leader, the protocol also needs to use timeouts to ensure progress.

This timeout needs to accommodate the duration of deploy transactions (or at least the variation of the duration).  Sizing this timeout conservatively means that faulty leaders will be detected more slowly.

Alternatively, we could split deploy transactions into a hint, which will initiate the deployment, and a final transaction, which will record the deployment on the ledger.

**Comment by binhn** [comment]
@muralisrini Since a deploy transaction is independent, I think we can optimize it and return successful if the validation (checking sig, cert, hash, etc) is successful. The actual build and launch container may be done on a separate channel that the validator works on without effecting the consensus timing.  

However, we still have to deal with the case where the invoke transaction has to wait for the deployment of the chaincode due to chaincode container crashes or has not been deployed (part of sync)

Thoughts?

**Comment by binhn** [comment]
I think we need 2 different timeouts: 1 for deploy tx, and 1 for invoke tx. Currently only 1 is defined in openchain.yaml as 30000ms = 30s. I think this is very long for deploy tx, but we need another property for invoke tx, which is much smaller, say 5ms.

**Comment by christo4ferris** [comment]
@corecode @muralisrini is this still an issue or can it be closed?

**Comment by corecode** [comment]
Still an issue.

**Comment by christo4ferris** [comment]
Moved to Jira https://jira.hyperledger.org/browse/FAB-120 closing
