### ISSUE TITLE
Add pkiID to PeerEndpoint for consensus usage

### ISSUE THREAD

**Issue by jeffgarratt** [hyperledger-archives/fabric#514]
Add the pkiID to the PeerID protbuf structure.  This value is sent through the HELLO message and is obtained from crypto.Peer#GetID.

**Comment by jeffgarratt** [comment]
Discussed with @tuand27613 and @adecaro.

**Comment by jyellick** [comment]
One problem I see with this, is that a `[]byte` is not a data type which is comparable.  This is going to cause some headaches where the `protos.PeerID` is already used as a key in maps.

I dislike converting `[]byte` into strings (via `base64.StdEncoding.EncodeToString`) but that is what obcpbft ended up doing with the block hashes so that those messages could be used as map keys.

Any thoughts on a better option to fix up the code which already depends on this structure as a map key?

**Comment by binhn** [comment]
Another problem is that security is not always on -- dev mode or certain deployment environments.  

We decided last week to use a simple peer ID (vp#) for pbft.

**Comment by jeffgarratt** [comment]
@binhn @jyellick @tuand27613 Could add it to the PeerEndpoint outside of the PeerID structure and make sure to only set if security is enabled.  Make sense?

**Comment by jyellick** [comment]
@binhn The problem with a simple (vp#) peer ID is that it's forge-able.  With security on, obviously we can prevent unwanted nodes from connecting to the network, but we cannot ensure that one node does not masquerade as another node by falsifying their peerID.

I think for PBFT in particular this is a problem, because a byzantine node could issue checkpoints or messages as another node, which has the potential to either overwrite an existing message or cause a new one to be ignored, depending on implementation.  In general, I think PBFT is broken if it is possible for one node to impersonate another.

@jeffgarratt What we do need inside the `PeerID` is something that uniquely identifies the peer and cannot be forged by a malicious peer.  Some sort of derivative of the certificate is likely a good choice, perhaps there is a string in the certificate which we could use which is also not forgable? This would solve both problems.

**Comment by jeffgarratt** [comment]
@jyellick @adecaro  the proposed pkiID is the hash of the enrollment cert used by the crypto system, so I presume this meets the criteria of a derivative of the cert?

**Comment by jyellick** [comment]
@jeffgarratt Yes, the only downside is that because it is a `[]byte`, it makes the message a lot less friendly to consume, as it loses it the comparable property, and can no longer be used as a map key.  Obviously this isn't the end of the world, the code which presently uses it as a map key could be updated, but if there were a happy solution where the message keeps its comparable-ness, it would reduce the amount of refactoring which needs to be done.

**Comment by jeffgarratt** [comment]
@jyellick any issues with it ouside of the PeerID, as part of the PeerEndpoint?

**Comment by binhn** [comment]
@jyellick 

> The problem with a simple (vp#) peer ID is that it's forge-able

We don't have to worry about that in dev mode nor in deployment where byzantine not used. The id is a simple string.

**Comment by jyellick** [comment]
@jeffgarratt I think there are three issues here:
1. @tuand27613 Needs access to the `pkiID` in order to do his validation work.  He can correct me if I'm wrong, but I believe having it in either location would work for him?
2. For consensus, peers are addressed by `PeerID`, this is what the `CPI` requires, but presently, the `PeerID` is a self reported string, and is consquently forge-able, even with security on.
3. Adding `pkiID` to `PeerID` fixes 1 and 2, but, a fair bit of code currently depends on the fact that `PeerID` is comparable, and can be used as a map key.

If we have to pick 2/3, I'd say 1 and 2 are the most important.  I was just hoping we could come up with a way to accomodate 3 as well.  Maybe @kchristidis can weigh in?

**Comment by jyellick** [comment]
@binhn Yes, with security disabled, I agree that a simple (vp#) scheme is just fine.  The problem I see, is that when security is enabled, we need to include some piece of unforge-able information in the PeerID, to prevent a peer which is allowed to connect as a validating peer, from deliberately reporting their own PeerID as someone else's.

Correct me if I'm wrong, but the `Name` field in `protos.PeerID` is self-reported by the connecting peer?  If so, then I think the problem outlined above stands.

**Comment by kchristidis** [comment]
This seems like a follow-up to the discussion that @jyellick, @jeffgarratt, and I had on Friday night.

What prevents me as VP from getting someone else's `PeerID` and `pkiID` and attempting to reconnect on the network as them?

I'll also include some commits that _might_ be relevant to the discussion here:
1. Add `cryptoHandle` to `PeerEndpoint` if `security.enabled == true`: https://github.com/kchristidis/obc-peer/commit/b469e4340270f914539bb0a0af71ca1d2b07715a
2. Undo commit `b469e43` (was hoping that better solution would come along), and use `PeerID` as the key for `handlerMap`: https://github.com/kchristidis/obc-peer/commit/9a591c8271db59a2a0454f6c5e8136e960798e78

**Comment by jyellick** [comment]
@kchristidis I think with the `pkiID` included, it would be fairly simple to add some code to verify that the `pkiID` in the `PeerID` matches the certificate of the incoming connection, but it's a good point that this is extra work and does not come free.

**Comment by kchristidis** [comment]
@jyellick Right, I don't know if anyone's working on that.

**Comment by jeffgarratt** [comment]
@jyellick @adecaro @tuand27613 @binhn what about a base64 encoded version in the PeerID structure?

**Comment by jyellick** [comment]
@jeffgarratt This was my first thought, and how we handle this for `BlockHash` in the PBFT consensus messages.  Maybe @tuand27613 can chime in, as I'm not sure how frequently this field will need to be deserialized back to an `[]byte`.  Assuming this works for others, it works for me.

**Comment by tuand27613** [comment]
I just need to pass pkiID as-is to the crypto Verify() function. Angelo and team use it internally to get to the cached ECert of the sender.

I'm ok with making pkiID a base64 encoded value.

@jeffgarratt  @jyellick  @kchristidis  @binhn

**Comment by adecaro** [comment]
@jeffgarratt I can modify Peer#GetID() to return directly a string, not a big deal!

**Comment by tuand27613** [comment]
@adecaro I second that.
@jeffgarratt @jyellick @binhn do we have consensus ? :-)

**Comment by jyellick** [comment]
@tuand27613 Works for me

**Comment by jeffgarratt** [comment]
@tuand27613 @jyellick @adecaro @binhn @kchristidis Spoke with @tuand27613, going to add a pkiID to PeerID which will be a string so it will still be comparable for map key usage.  If security is off, this will be empty.  The initial version will base64 encode the bytes for now, but @adecaro suggested he could change the crypt.Peer#GetID to return a string instead of bytes in the future, which will require the removal of the proposed base64 encoding when that is merged.

**Comment by jeffgarratt** [comment]
Created #537 and @kchristidis is reviewing.
