### ISSUE TITLE
Revisit sync TODO comments in NOOPS

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#529]
We have some TODO comments related to sync in NOOPS that we need to revisit

**Comment by binhn** [comment]
@jeffgarratt @jyellick Jeff and Jason, what you talked about yesterday seems related to this. Could you comment on the work remains for noops sync.

**Comment by jyellick** [comment]
@jeffgarratt @binhn 

The outstanding piece I was noticing was not implemented was the startup hello sync.

When a new `noops` consenter starts up, it should sync to the highest available block and begin processing transactions from there.

This would serve a two-fold benefit, to allow a new `noops` consenter to begin participating in an existing test network, and also give us some basic test coverage of state transfer.

The state transfer work done in issue #291 was factored out into its own package (`consensus/statetransfer`) which should be utilized.  My understanding is for `noops` there is a hello message from every consenter which advertises their highest available block.  For state transfer to function, as written, it must be supplied a block number and a block hash to sync to.  This leaves us three options.
1. Modify the state transfer to allow syncing to a block target with no hash.
2. Modify the hello message to include the block hash
3. Modify `noops` to manually fetch the initial block, then allow state transfer to complete

My vote would be for solution 2.

Once the block hash is available, utilizing the state transfer is very easy, simply register a callback for state transfer completion, initiate the state transfer, and supply the known block number and block hash along with the peer or peers to fetch from.  The state transfer will execute asynchronously invoking the callback once the state has caught up to the block specified.  There are additional hooks for listening for state transfer errors, and methods for recovering from them, but I think this can probably be ignored for `noops`.

Once a decision around the question above is made, I'm happy to complete this work, or I can provide a little additional documentation on the state transfer if someone else would like to.  Note that there are some naming changes in the pipeline from issue #577 which exist in an external branch, but are pending integration into master.

**Comment by binhn** [comment]
> 1. Modify the hello message to include the block hash

@jyellick The HelloMessage currently has blockNumber, would that work?  And I thought Jeff implemented sync upon hello if needed. @jeffgarratt please comment;  otherwise, I agree with your analysis, and we should do #2 if we haven't done any sync there.

```
message HelloMessage {
  PeerEndpoint peerEndpoint = 1;
  uint64 blockNumber = 2;
}
```

**Comment by jyellick** [comment]
@binhn The block number is half of what state transfer wants today, it also wants the block hash.  The idea being that the only way state transfer can verify that it is receiving correct blocks and state is by knowing the block hash of the highest block.

We could modify the state transfer to allow syncing to a block height with no block hash, but I don't see a lot of value of doing that outside of noops.

If we were to add the block hash to the hello, not only would this give us network error protection for the state sync in noops, this would also be a help to PBFT to catch up faster when a node first starts up.

**Comment by jyellick** [comment]
@jeffgarratt Per our discussion today, I'll wait for you to add the block hash to the hello message. Once the block hash is there, I can integrate state transfer into `noops`, or, you're welcome to take a shot at it, just let me know.

**Comment by binhn** [comment]
@jyellick I just realized that we 've been talking about state transfer, but for NVP, we don't need state, only the blocks. Is the code replicate both blocks and state?

**Comment by jyellick** [comment]
@binhn The code replicates both state and blocks.  Since the block contains a state hash, replicating the state in addition to the blocks is relatively straightforward.

Edit:  Sorry, @binhn, I think I missed the point of your comment, that in order to use the `statetransfer` package for NVP block replication, we would need it to only grab the blocks.  That isn't what happens today, but I think it would be a fairly simple modification.

**Comment by kletkeman** [comment]
@binhn Just curious why you suggest that state transfer would not be needed by NVPs? I am under the impression that applications and monitors should hang off of NVPs and timely state updates will be critical for those ...

**Comment by binhn** [comment]
@jyellick not sure if you are working on this with Jeff?

**Comment by jyellick** [comment]
@binhn  Per our discussion last week, state transfer expects a block hash and block number for sync.  Rather than modify state transfer to handle the degenerate `noops` case, we decided that adding the block hash to the hello message would be a simpler path.  @jeffgarratt volunteered to add this enhancement to the hello message, but I think he's had more important things on his plate, so the state transfer integration work is still pending.

**Comment by jyellick** [comment]
@binhn 

After some discussions with @jeffgarratt we had come up with a design that seemed to make sense for `noops`, however, as I've attempted to implement I've come across a few flaws that seem like they may be fatal.

The flow was proposed as follows:
1. Backup VP connects to the network, and receives a HELLO message from the Primary
2. Backup realizes that its block height is at 5 and the primary is at 10
3. Backup initiates state transfer, state transfer completes, backup is now at block 10
4. Backup participates normally, executing transactions

The problem here, is that in `noops` (unlike, `obcpbft`) transactions have no accounting associated with them.  Assume in step 3, the backup does retrieve a correct state and block to block 10.  The backup has no way to know whether it has already missed transactions which are to be incorporated into block 11.  Similarly, it's possible that the primary commits a block after the hello message, so instead the backup ends up syncing to block 11.  Potentially, the backup could look back through the previous block and try to identify transactions which have already executed, but this seems like a poor solution to me (and does not address the other case).

The more I look at this, the more I'm inclined to agree with @corecode and @jeffgarratt, that `noops` simply needs to be deprecated in favor of something like `N=1` pbft.  In order to support state transfer and in order to support concurrently sending different requests to different validators, `noops` is going to have to become much more sophisticated than it is today.
