### ISSUE TITLE
Test of John Wolpert User Story1: Epic: Backlog Manager

### ISSUE THREAD

**Issue by jwolpert** [hyperledger-archives/fabric#552]
As a product manager or developer on Blockchain, I need a way to quickly enter Epics, User Stories, nested substories and tasks to a common backlog, so that I can maintain a single point of truth and know what we are doing and NOT doing on the various projects in the group.

**Comment by jwolpert** [comment]
So what I'm seeing so far is that this doesn't allow me to put any stories under this one, so fail as an Epic...(and we'd need an "Epic" Label (among other things, like Milestone 4 is the last one here).

**Comment by jwolpert** [comment]
Looks like I can only assign one person at a time...no ability to assign followers.

**Comment by frankyclu** [comment]
epics starts from ideas, and they need to be debated before becoming real user stories ----> another reason to not use github for that

**Comment by markparz** [comment]
That is true since these are "issues" basically a breakdown to task level, you can't have mulitple assignees.  Another unfortunate piece is that you can't create columns and organize via milestones, everything is done via label. ... it's a very limited tool ... We have to think it out well and use the labels to filter to get the information presented in a way to see it. If you want to do an Epic and assign the stories, then tasks, have to use the links inside like: 
- [ ] #515
