### ISSUE TITLE
Flow of sandbox to production is unclear

### ISSUE THREAD

**Issue by bmos299** [hyperledger-archives/fabric#553]
I believe the flow of the environments of dev (SandboxSetup.md) to prod (DevnetSetup.md) has to made more transparent and obvious as to what and why things are occurring.

Let me propose the flow (and thanks to @muralisrini  for discussing with me)

As someone walking through the docs and attempting to understand the usage and actually setup the entire procress.  They need to see the following,
1.  running a dev environment on a single system
   this is pretty much in sandbox as a chaincode dev option, no docker (pretty much in SandboxSetup.md) now. 
2.  running on a single system and not in a dev environment
   explain the difference and what is now occurring
   docker now running the chaincode
   explain docker usages in detail in this section with a picture
3.  running on a single system with multiple peers using a network
   running the peers in docker to simulate a network of peers on the same physical hardware (basically DevnetSetup.md)
4.  running a production type system with several pieces of real hardware using a real network
   routers, different subnets, do not to start under docker yet docker still will run the chaincode itself

Following this flow and naming the .md files accordingly and sequentially pointing to the next step will allow the consumers to truly see the flow and our intent for each step.

**Comment by binhn** [comment]
Please change the doc and add more docs as you see fit.

**Comment by kletkeman** [comment]
Hear, hear! Well put @bmos299. The current documents serve very well, but system engineering documents would help a great deal in transitioning to larger distributed networks of independent servers / vm's etc.

**Comment by christo4ferris** [comment]
@bmos299 I've done a considerable refactor of the docs, and tried to call out the various approaches to standing up a network, etc. While I think that there is still room for improvement, and possible further refactoring and clarification, it is an improvement over the docs of March/April which had lots of redundant, overlapping and often conflicting information, depending on what mode of operations one was using. I'm going to close this. However, feel free to re-open if you think that there's more to be done specifically (rather than generally). Also, too, PRs are encouraged if you have specific suggested changes.

**Comment by bmos299** [comment]
@christo4ferris agreed.  The doc has greatly improved, but still not where we want it to be.  The team will open new issues as needed.   Thanks for all your comments on the docs.
