### ISSUE TITLE
Change devops endpoint APIs

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#558]
We are considering deprecating the current devops APIs since they are not restful:
POST /devops/deploy
POST /devops/invoke
POST /devops/query

And replace them with:
deploy: POST /chainchode
invoke: PUT /chaincode/<id>
query: GET /chaincode/<id>
terminate: DELETE /chaincode/<id>  (later)
instantiate: POST /chainchode/<id>  (later)

The current API endpoints will remain but will be documented as deprecated. New app is recommended to use the new APIs

**Comment by sumanair** [comment]
Binhn, what are the timelines you are looking at for this change? We are leveraging these APIs as part of the IoT effort so knowing the plans would help us plan better.

**Comment by angrbrd** [comment]
Hi @sumanair. This will likely change within the next week. Thanks.

**Comment by mastersingh24** [comment]
I think this is actually a mistake.  Invoking chaincode is not equivalent to a PUT call for a RESTful resource.  Invoking chaincode is more analogous to a JSON-RPC call and POST is actually a more appropriate construct.  And actually, the same really holds true for all of the other chaincode "actions".

**Comment by binhn** [comment]
@mastersingh24 my thought here is that invoking chaincode is actually updating its state, so a PUT would be appropriate. POST is used for everything in RPC as you said and not what we have in mind here

**Comment by angrbrd** [comment]
@mastersingh24, I tend to agree with your opinion. I think optimally, the best approach would be to have a single POST /chaincode and be able to determine which operation we want (deploy, invoke or query) from the payload. However, we can not do that as we simply pass a function name in the payload, which is not enough for us to determine what we want to do (deploy or invoke or query). It's just any string for the function name so it's not descriptive enough.

I would say that the next best thing would be to do exactly what we have, but replace the word "devops" with the word "chaincode" and have the below, and have three separate endpoints handing the separate operations.

-- deploy: POST /chaincode/deploy
-- invoke: POST /chaincode/invoke
-- query: POST /chaincode/query

@binhn , if we have the PUT updating the chaincode state, then the endpoint would need to be:

-- PUT /chaincode/{chaincode_id}/{chaincode_state_variable_name}

That is a very inconvenient API as the chaincode_id will be a huge hash returned from the deploy operation.

I also disagree with the query to be GET /chaincode. We will always have a payload for the query operation and having a GET request that can have a varying response based on an incoming payload is not appropriate REST.

@binhn , @mastersingh24 . Thoughts?

**Comment by muralisrini** [comment]
@binhn : sounds to me above logic is sound. We are actually sending arbitrary size payloads for invoke and deploy for which PUT feels more unRESTful as well being impractical for human usage (though I liked the simplicity of using verbs to denote action...)

As @angrbrd indicates, perhaps just get rid of "devops" from the URI ?

**Comment by mastersingh24** [comment]
@angrbrd  : I like

-- deploy: POST /chaincode/deploy
-- invoke: POST /chaincode/invoke
-- query: POST /chaincode/query

I agree that given the way things work that seems like the best option

**Comment by binhn** [comment]
For these endpoints, it is easy to think in terms of RPC, and if that's what we want to do, don't call it REST. It is not straight forward to be able to apply restful styles to certain scenarios.  Do we have to provide REST?  no, but we need to be consistent in our API; we can't call it REST and mix in junks like "POST /chaincode/deploy"

**Comment by angrbrd** [comment]
@binhn , I completely agree with the above, but my points still stand. The best solution is POST /chaincode for ALL three operations. That is RESTful and easy to use. The problem is, we will have to modify our payloads to specify unambiguously what operation is being requested. Currently, we can not identify which one we want with the function name. I understand that is not proper, but that is still a better approach than specifying a huge URI that has the chaincode hash in it. That seems worse to me, personally. Very unwieldy for the end user. 

So do we want to change the chaincodeSpec to codify the operation (deploy/invoke/query)? It will be another enum field holding the same options as the generated Transaction.

message Transaction {
    enum Type {
        UNDEFINED = 0;
        CHAINCODE_NEW = 1;
        CHAINCODE_UPDATE = 2;
        CHAINCODE_EXECUTE = 3;
        CHAINCODE_QUERY = 4;
        CHAINCODE_TERMINATE = 5;
    }

In that case, we could go to POST /chaincode for everything. @muralisrini , I think that would be a simple change to add another enum to the protobuf. I think nobody except the API would be using it to unpack and extract from the payload. All the other code will be unaffected as the field would not be required. Do you think that may make more sense here?

@mastersingh24

**Comment by kletkeman** [comment]
I like POST /chaincode/deploy|invoke|query

I wonder, though, if it would be possible to define a vocabulary that a chaincode could service ... as in registering something like:

/manifest
/manifest/containers
/manifest/containers/ID
... and so on ...

Obviously, only /manifest need be registered by the chaincode ...

Is something like that possible at all?

**Comment by mastersingh24** [comment]
@kletkeman - anything is technically possible but nothing like that is implemented today

**Comment by binhn** [comment]
> The best solution is POST /chaincode for ALL three operations. That is RESTful and easy to use.

@angrbrd what is your definition of a restful API?

I found these best practices:
http://blog.octo.com/en/design-a-rest-api/
http://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/
http://codeplanet.io/principles-good-restful-api-design/
https://github.com/RestCheatSheet/api-cheat-sheet#api-design-cheat-sheet

**Comment by kletkeman** [comment]
@binhn The codeplanet reference is excellent and shows why POST is best for chaincode API. The API is not resource centric, but rather function centric, which makes it an RPC API more than RESTFUL API. Which is not to say that there is something wrong with the chaincode interface, just that it requires significant attention to API design at the contract level to choose certain patterns (singleton managing many assets, one contract instance per asset, and so on.) Since there are so many ways to deal with this, the contract designer must choose a set of invoke and query APIs that make the most sense for the pattern, and so there is no way to cast these as pure restful as only the singleton pattern could possibly answer for more than one resource type. And even if it could, rocksdb does not make it possible (yet) to get all assets of a specific class (i.e. no SPARQL or SQL like queries that I know of.)

Further, I am exploring patterns where you have a single key per asset state and where you have multiple composite keys per asset state. The former updates the entire asset at once and the latter updates properties. The former would be ok with PUT or PATCH, depending on how the asset state and the interface are modeled ... but that is opaque to the system and only visible inside the contract itself, so modeling all invokes as POST stills makes more sense than pretending that the contract can be forced into a PUT or a PATCH behavior.

**Comment by srderson** [comment]
+1 for changing `devops` to `chaincode` but it sounds like everyone agrees with that :)

+1 for @binhn's comment "it is easy to think in terms of RPC, and if that's what we want to do, don't call it REST." If we use RPC, should we follow the [JSON RPC 2.0 spec](http://www.jsonrpc.org/specification)? This would imply a single endpoint such as `/chaincode` and I can POST a body such as
`{"jsonrpc": "2.0", "method": "invoke", "params": {"function": "deposit", "data": [...]}, "id": 1}`
or
`{"jsonrpc": "2.0", "method": "deploy", "params": {...}, "id": 1}`

I personally prefer REST APIs and we have several existing REST endpoints, `/chain`, `/transactions`, `/registrar`.

Proposal for a REST like chaincode API.

For managing chaincodes
POST `/chaincode` - deploy a new chaincode
DELETE and PUT `/chaincode/:id` in the future when we support such concepts

For running chaincode functions
POST `/chaincode/run/:id/:function` - invoke
GET `/chaincode/run/:id/:function` - query
with a body including parameters.

For everyone voting POST `/chaincode/deploy|invoke|query|terminate|instantiate`, as a user, I probably wouldn't be that bothered as long as it's well documented. My only question is if we're mixing two concepts, the management of the chaincode resource and the running of chaincode functions? Sometimes I find RPC documentation a bit hard to digest when there are many methods (concepts) under a single endpoint.

**Comment by kletkeman** [comment]
@srderson I'm glad you called it "REST like" because a function is not a resource and so the REST analogy is seriously mitigated.

If we want to go for a more pure REST model, then perhaps we need a way for a chaincode to bind to a nickname and namespace such as: 
/chaincode/nickname/cars/... 
/chaincode/nickname/cars/VIN/...

When spinning up multiple instances of the same contract, it would be necessary for each instance to bind to a class of assets or a single asset (e.g. a car's VIN) ... but that should be manageable.

Personally, I would vote for this option. But if it is too much to do or is seen as flawed in some other way, then I would vote for a simple RPC mechanism like we already have. Tweaking that with /chaincode/ is fine ... although perhaps we should consider using /contract/ instead ... after all, chaincode is a techy expression of the physicality, whereas contract is what a chaincode logically implements ...

**Comment by angrbrd** [comment]
It is not clear to me if we have reached an agreement on how this should be addressed. I will see that @binhn and @srderson and myself level set tomorrow to decide on how to address this in the most appropriate manner. We are freezing the code next week so if we are going to change this, it needs to happen asap.

**Comment by angrbrd** [comment]
@binh, @srderson, and myself touched base on this issue and decided on the following.

(1) The existing endpoints of /devops/deploy, /devops/invoke, and /devops/query will remain but will be documented as deprecated whenever the new endpoint in (2) will be introduced.

(2) A new endpoint POST /chaincode will be introduced and follow the JSON RPC 2.0 spec to trigger a chaincode deploy, invoke, and query.

(3) This is not a high priority issue at this time and will be addressed in the next sprint. Therefore, not marking as a "bug" at this time.
