### ISSUE TITLE
Fix Docker/Vagrant issues related to multi-validator network

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#567]
There are a couple of issues (see [here](https://github.com/openblockchain/obc-peer/issues/463#issuecomment-175739508)) that prevent Tuan from testing a multi-validator network using his Docker Compose setup.

@tuand27613 is working with @muralisrini and @jeffgarratt to resolve this. Please use this thread to post updates.

**Comment by tuand27613** [comment]
The docker container running obc-peer has trouble reading consensus/obcpbft/config.yaml, particularly the value of general.N

The workaround is to set env OPENCHAIN_OBCPBFT_GENERAL_N  when starting the container.

I have tried adding "." and "%GOPATH/src/github.com/openchain/obc-peer/openchain/consensus/obcpbft" to Viper's AddConfigPath() to no effect.

I've also tried copying config.yaml to obc-peer/ and to $GOPATH/bin (since this is where docker puts the executable)  but again to no effect

**Comment by kchristidis** [comment]
@tuand27613: This has to do with how `viper` parses the path listed in `AddConfigPath()`, which is always relative to the caller. (A very odd design choice if you ask me.)

The argument to `AddConfigPath()` is a string, so there's no way `%GOPATH` is parsed right. Try to do `../src/github.com/openchain/obc-peer/openchain/consensus/obcpbft` in `AddConfigPath()`, since this is the relative path that would take you from `$GOPATH/bin` to the `obcpbft` package.

**Comment by tuand27613** [comment]
The network can be brought up consistently now. 
The 4 VP, obcca and cli containers start up and I can issue the chaincode deploy/tx/query commands without something crashing.

There are 2 types of issues left:
1. hardware/virtual machine related.  I had to increase vagrant 4M->8M memory and 2->3 CPUs to handle grpc connections lost and out of memory crashes
2. obc code issues:
- still can't figure out why we can't read from obcpbft/config.yaml  . I implemented @kchristidis ' suggestion and it still won't function right. Not a big problem right now
- obc-peer login wants create directory /var/openchain/production/client  but fails because /var/openchain/production isn't created.  I changed main.go to use os.MkdirAll() instead of os.Mkdir() and that fixed it.  I need to find out who's supposed to create /var/openchain/production which is OPENCHAIN_PEER_FILESYSTEMPATH
- The 2nd request received by consensus has the same digest as the first (already processed) request. @jyellick also sees this running outside of docker-compose.  I'm putting more debug statement to see where the error creeps in

**Comment by tuand27613** [comment]
@jeffgarratt  will try to put all this into a behave test.

**Comment by tuand27613** [comment]
vp1-3, obcca and cli containers now start consistently.  Next issue is that when i issue the chaincode deploy,  either one of the chaincode containers does not start or one of the existing containers stops or grpc hiccups.

Trying to release more resources on my machine to see if that helps vagrant/docker

**Comment by tuand27613** [comment]
All docker containers now come up consistently.

Seeing problems with :
- TLS failures during peer login. creating #580 to track
- 1 out of 4 validating peers could not match message digest. Talked to @muralisrini who suggested getting the pull request for #520 and retrying

**Comment by tuand27613** [comment]
bug from #580 fixed.
latest fetch from obc-peer/master took care of #520 

Running into a "transport closing", "getEnrollmentCert parse error" @adecaro  investigating

running without security,  sieve seems to not do the actual cpi.ExecTXs() @corecode  investigating

**Comment by corecode** [comment]
Sieve issue fixed in 089388f562f29ec543e6d95bc5f6e888c66e002e

**Comment by tuand27613** [comment]
@adecaro  added code to better trace #592. Seems to be that we are passing in a blank vkID to Verify().
Just merged with latest openchain/master and re-trying

**Comment by tuand27613** [comment]
submitted [PR 615](https://github.com/openblockchain/obc-peer/pull/615) to fix  cpi.Verify().

We die when receiving a view-change from self.  PkiID not populated so crypto verify() fails so we ignore

**Comment by tuand27613** [comment]
sieve now works with security enabled.
Now pursuing classic where I'm seeing current view not matching between peers

**Comment by tuand27613** [comment]
classic , batch with security enabled:  I see the correct sequence of pre-prepare/prepare/commit and execution as well as view changes.

But, the logging "enhancements" took away all stdout output so I can't see the actual results of the chaincode invoke. I know that's being worked on today so I'll try again after that PR makes it to obc-peer.

In the mean time, I'll try to see what I can do locally to fix go-logger.

**Comment by tuand27613** [comment]
Batch/classic/sieve now run with security enabled .

running with my compose-consensus-4.yml setup and with the `behave` test framework.

**Comment by kchristidis** [comment]
Good to close this @tuand27613?

**Comment by tuand27613** [comment]
good to close.
