### ISSUE TITLE
obc-peer command-line flags do not (can not) work

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#578]
The Viper/Cobra option-processing system used by openblockchain
apparently does not support the idea that command-line flags are
equivalent to nested keys from config files. See for example
recent conversations here: https://gitter.im/spf13/viper

This means that many (if not all) of the obc-peer command line
flags do not work, since the flag X_Y_Z is distinct from the
nested key X.Y.Z., and the codes that I've examined only look for
the nested key.

You can see this for yourself by putting lines like the following
at the top of the `serve()` function in main.go:

```
fmt.Println("SERVE VIPER peer_tls_key_file", viper.GetString("peer_tls_key_file"))
fmt.Println("SERVE VIPER peer.tls.key.file", viper.GetString("peer.tls.key.file"))
```

and call the obc-peer as

```
obc-peer peer peer-tls-key-file=foo.bar
```

The output is

```
SERVE VIPER peer_tls_key_file foo.bar
SERVE VIPER peer.tls.key.file testdata/server1.key
```

that is, the nested key is taken from the openchain.yaml, in spite of being
'overridden' on the command line.

**Comment by bcbrock** [comment]
My description of the issue is so vague that I can't remember what I was complaining about any more. Closing.

**Comment by kchristidis** [comment]
I spent the past couple of days looking into the `pflag`, `viper`, and `cobra` packages. I may be missing something, but I don't see anything wrong with the `viper` package itself here. Rather, the issue seems to be in the way we use it.

Specifically:

We bind Viper key `a_b_c` to flag `a-b-c`. We then use/set flag `a-b-c` and expect Viper key `a.b.c` to be modified. (So as to override config value `a.b.c`, which is binded to the `a.b.c` key.)

This is not reasonable.

I _assume_ that part of the confusion stems from the use of these commands:

```
replacer := strings.NewReplacer(".", "_")
viper.SetEnvKeyReplacer(replacer)
```

and an expectation that this changes the `a_b_c` key to `a.b.c`.

However what `viper.SetEnvKeyReplacer()` does here is to simply bind any `A_B_C` **ENV** variables to `a.b.c` keys. I tested this by setting up a MWE: https://github.com/kchristidis/golang-experiments/tree/viper

The solution here is to rename all Viper keys in our code from the `a_b_c` format to the `a.b.c` one.

Then the `a-b-c` flags will bind to `a.b.c` keys. Thanks to the `SetEnvKeyReplacer()` call the `A_B_C` ENV flags also map to the `a.b.c` keys. And the nested `a.b.c` YAML config values map to the `a.b.c` keys as well.

So you'll be able to do `executable command --a-b-c=FOO` (or `A_B_C=foo executable command`) to override the YAML variable `a.b.c`.

@bcbrock let me know if this is the behavior you wish to see. (And if so, feel free to reopen the issue; I 'll push a PR for it.) @jeffgarratt do you see anything wrong in my findings or proposal here?

**Comment by bcbrock** [comment]
@kchristidis Have you tested your proposal? When I first discovered this I went on a Viper chat room (can't find it now unfortunately) and the consensus was that command line flags were disjoint from env. variables and YAML.

**Comment by kchristidis** [comment]
@bcbrock I have, and I included the link in the previous post.

You can map a command line flag and an ENV to the same Viper key.

```
./golang-experiments test
0 # reads the YAML about.version
./golang-experiments test --about-version 2
2 # overrides the YAML with the flag
```

**Comment by lehors** [comment]
So, I confirm what @kchristidis said here. If the binding is done as in `viper.BindPFlag("peer.tls.enabled", flags.Lookup("peer-tls-enabled"))`
instead of
`viper.BindPFlag("peer_tls_enabled", flags.Lookup("peer-tls-enabled"))`
The problem goes away.

We then have the following precedence: command line option, env variable, yaml file, and finally built-in default in the code.

This being said the name of the default and override setting "logging-level" is a bit confusing because unlike similar names it does NOT map to nested properties in yaml. So, this one needs to be left alone.
