### ISSUE TITLE
Failed invokes during load test

### ISSUE THREAD

**Issue by jpayne23** [hyperledger-archives/fabric#599]
Summary: Running a load test which uses /devops/invoke and devops/query and too many invokes failed.

Priority: High

Keywords: failed invoke

Description:

I was running a load test which uses devops/invoke and devops/query to create a vehicle through the Car Lease Demo application. This was done using a single validating peer network with NOOPS.

Test conditions were:
- 1000 runs
- 2 threads
- 1 second interval
- Max error count = 10

Abstract:

openblockchain/obc-test#19

Configuration:

Scenario:
openblockchain/obc-test#19

== Recreate Steps ==

openblockchain/obc-test#19

== Expected Output ==

I expected the load test to create 1000 vehicles with no errors.

== Observed/Actual Output ==
Failed the load test with 11 errors at 62% completion.

Log Data/Other Information attached

[create_vehicle_load_test_04-2.zip](https://github.com/openblockchain/obc-peer/files/117850/create_vehicle_load_test_04-2.zip)
- see attached openchain.yaml file used (security is enabled)
- see attached txt in zip containing the error message from obc-peer

See issue openblockchain/obc-test#19 for link to test artifacts

**Comment by binhn** [comment]
@angrbrd could you please investigate

**Comment by angrbrd** [comment]
The peer log has the following error message:

[31m15:31:25.920 [peer] handleChat -> ERRO 1ad[0m Error handling message: Failed to begin transaction with the ledger: Another TxGroup [seconds:1454599885 nanos:752346817 ] already in-progress

This issue is a duplicate of #572, as that issue is also reported on repeated and rapid invoke of chaincode with the same error message. @jpayne23 do you agree? If so, please mark as dup and close this one.

**Comment by angrbrd** [comment]
I discussed with @jpayne23 and we agree that this is a duplicate of issue #572 . I am closing this one as a duplicate.

Thanks.
