### ISSUE TITLE
large memory leak executing http://<peeraddress>:5000/chain

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#608]
running curl http://127.0.0.1:5000/chain in a loops causes obc-peer to lose memory rapidly and crash. The underlying method is "s.ledger.GetBlockchainInfo()" called in api.GetBlockchainInfo. Commenting that out and returning pb,BlockchainInfo{Height: 1} shows no mem leak. Assigning to @srderson to assign appropriately.

This was found while investigating #589

**Comment by muralisrini** [comment]
Should have mentioned - @jeffgarratt found this leak and may have additional insight

**Comment by srderson** [comment]
I'm continuing to investigate, but I've discovered that the reproducibility of this bug seems to depend on the last block in the chain. If the last block contains a single deploy transaction, the crash will happen after around 300 GET /chain invocations. If the last block contains a single invoke transaction, it's possible to run 100,000+ GET /chain invocations without issue.

**Comment by srderson** [comment]
I should also mention that I'm using the default buckettree configuration to reproduce the issue.
