### ISSUE TITLE
The peer.gomaxprocs property in yaml not used

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#610]
In openchain.yaml, we define `peer.gomaxprocs: 2`, but in the code, we are not using it. This is important for performance analysis to find the best profile for obc-peer.

```
func main() {
    runtime.GOMAXPROCS(2)
...

    viper.BindPFlag("peer_gomaxprocs", flags.Lookup("peer-gomaxprocs"))
```

**Comment by binhn** [comment]
@adecaro FYI, we need the same config for obc-ca

**Comment by adecaro** [comment]
@binhn Addressed in obc-ca with PR #628

**Comment by bcbrock** [comment]
I would request that when this support is added, the default should follow the current GOLANG defaults, that is, unless otherwise overridden by the user the code should not set GOMAXPROCS, but simply allow the system to use its default value. Currently this means that the obc-peer will be able to use as many threads as there are CPUs on the system.

I'm also saying please don't override this in the default YAML file (but maybe put a comment demonstrating how to do it).

**Comment by adecaro** [comment]
@binhn, I checked and I can confirm that the property is used by the membership service.

**Comment by binhn** [comment]
@bcbrock @adecaro I set the config to -1 to use the system default setting, which is the same as the number of available cores.
