### ISSUE TITLE
obc-ca: multiple query requests to obc-peer fails at obc-ca

### ISSUE THREAD

**Issue by mrshah-at-work** [hyperledger-archives/fabric#650]
Concurrent query requests to peer when using obc-ca fails with the following error:

```
status code: 400 
{"Error": "sql: database is closed"}
```

Works fine when the queries are sequential (no concurrency) on a secured network.
Also works fine with concurrent requests if the networks is insecure (no obc-ca involved).

**Comment by adecaro** [comment]
@mrshah-at-ibm Do you have a stack trace or log that can be analyzed? Do you see the error at the obc-ca level?

**Comment by srderson** [comment]
Based on discussion this morning

@adecaro will add synchronization the InitClient and CloseClient functions. This should prevent the error, but slow down queries.

To improve performance, we need to create sessions in devops so that we do not open/close clients for every request. A new sev2 issue will be opened to implement this so performance is improved.

**Comment by binhn** [comment]
@mrshah-at-ibm this is ready for retest

**Comment by srderson** [comment]
@mrshah-at-ibm confirmed that the issue is now resolved.
