### ISSUE TITLE
state transfer test bed

### ISSUE THREAD

**Issue by tuand27613** [hyperledger-archives/fabric#652]
After talking with @jyellick ,  we can try these scenarios:
1. a validating peer arriving late.  Given a set of 5 peers, start peer1-4, execute some number of transactions, start peer5 and execute a few more transactions, finally, query chain height on all peers. Value should be the same for all peers.
2. a peer "dropping out" and re-establishing itself. Given a set of 5 peers, start peers1-5, execute some number of transactions, make peer1 drop (either stop it or force feed a nondeterministic error), execute some more transactions and finally, check height again.

First step is to see what can be done in a `behave` set up

**Comment by jyellick** [comment]
I think this should be doable with a total of 4 peers as well if need be, as PBFT should still make progress with just 3 peers.  If you are thinking noops, that testing will fail until #529 closes.

We also discussed setting up a state transfer test via sieve, not sure if you were planning on opening an issue for that or not, let me know if you'd like me to.

**Comment by tuand27613** [comment]
you're right @jyellick that 4 peers would work, I wanted to throw in an extra little twist.

I'm starting off with sieve.  Once that's automated,  switching to batch/classic/noops is flipping a bit in the test config.

**Comment by tuand27613** [comment]
the manual docker-compose setup - start obcca, 5 vp, 1 vp delayed start is working.  Now to translate that to `behave`

**Comment by jyellick** [comment]
@tuand27613 By 'state transfer test via sieve', I meant the following additional test:
1. Start a network of 4 sieve nodes.
2. Deploy a chaincode
   - On invocation, this chaincode should increment a state value by either 0 or 1, randomly
   - Note that because there are only two possible outcomes, f+1 replicas will agree on an output.
   - For any replicas which do not have the agreed upon output, state transfer will have to occur
3. Invoke the chaincode some number of times, 10? 20?
4. Verify that all peers reach the same state and block number

Maybe @corecode can verify that this would be a valid test, but if so, this would exercise state transfer many times in succession, as well as test the non-deterministic filters in sieve.

**Comment by corecode** [comment]
sounds right

**Comment by tuand27613** [comment]
with network of 4VPs, 3 starting simultaneously, 1 delayed ... vp3 correctly sends get_sync_block but other vp die with out of memory errors, consistently around call to peer.SendBlock()  ... trying various things to make sure it's not  my docker setup

**Comment by tuand27613** [comment]
uint underflow at https://github.com/openblockchain/obc-peer/blob/master/openchain/peer/handler.go#L432

since i is a uint , i-- past 0 gives you uint.maxValue so the loop never ends.

fixed in my branch.

Now getting error in statetransfer code, asking for sync blocks 6 - 0 from one vp,  10 - 0 from another vp then panicking

**Comment by tuand27613** [comment]
opened #676 and #680

**Comment by tuand27613** [comment]
#676 #680 closed.

scenario 1 listed above is now part of the `behave` test bucket.
