### ISSUE TITLE
Function getTempStateHash()

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#68]
We need a function to return the current temporary world state hash for consensus; that is, the hash of the state of the current block result. Consensus will call this function at the end of executing the block.

**Comment by kchristidis** [comment]
We should probably differentiate here between the **actual** world state hash, i.e the one that corresponds to what is committed in the blockchain, and the **candidate**/temporary world state hash, that corresponds to the state after the transactions in the block have been executed (but not agreed upon yet). What we seek here concerns the latter.

Let me know if I'm wrong.

**Comment by manish-sethi** [comment]
Yes @kchristidis, my understanding is same as yours. The committed state hash is present in last committed block and candidate/temporary state hash needs to be computed.

@binhn, We already have this method available. However, going forward we may need to experiment with the underlying approach of computing state hash for performance improvements. @srderson and I had discussed this and there is another issue #41 opened for this.

@binhn, @srderson Right now, we have the state structure and methods on this structure for modifying state and calculating hash etc. within custom code. I think that we need to define the structure in protos because, the structure needs to travel across nodes for node sync up etc. Also, do we need to expose a few methods on state in grpc? - or is there an alternate mechanism that we plan to expose to a transaction to modify state?

**Comment by binhn** [comment]
@kchristidis yes, i updated the description to include your comment

**Comment by binhn** [comment]
@manish-sethi the use of this function is local, and I don't know yet if exist cases for remote to provide the function in grpc. The only case that I thought would require remote is the API for external usage. Thoughts?

**Comment by manish-sethi** [comment]
@binhn yes, as far as this function is concerned the uses will be local. 
I guess, my comments are misplaced here and created a confusion. My comments were more related to the interaction between transaction code and state object and transfer of state for peer sync up.
Sorry for the confusion.
