### ISSUE TITLE
Always return ok when invoke chaincode even I give a wrong function name.

### ISSUE THREAD

**Issue by genggjh** [hyperledger-archives/fabric#835]
I am testing the chaincode_example02, find the REST API /devops/invoke returns ok message and create new transaction even if I provide a wrong function name in the ctorMsg.

But from the source code logic, I think we should get error message like: "Received unknown function invocation".

And the transaction has been created which really does not make sense.

**Comment by ghaskins** [comment]
I second this

**Comment by bcbrock** [comment]
@ghaskins Reading between the lines, are you suggesting that you prefer/require a protocol that blocks on invoke transactions until the transaction is known to be committed to the blockchain? Otherwise I'm not sure how one would separate parameter checking from execution of the chaincode? BTW, I think it would be a good idea to provide this "blocking" idea as an option to the invoke API.

**Comment by ghaskins** [comment]
@bcbrock yes, at least as an option.  I think this would minimally help with debugging.

**Comment by genggjh** [comment]
Anyone know how the DAH handle this? IMO, we need support sync and async invoke API both.

**Comment by srderson** [comment]
@angrbrd Can you investigate this in the REST API? If it's something lower level, please reassign

**Comment by muralisrini** [comment]
@genggjh @srderson @ghaskins @angrbrd ... this may be better candidate for consideration in the SDK...

**Comment by srderson** [comment]
@genggjh DAH made use of the events mechanism to listen for changes. https://github.com/hyperledger/fabric/tree/master/events

@muralisrini +1, this is synchronous API is likely a job for the planned SDK.

**Comment by mastersingh24** [comment]
Let's assume that we don't do anything to actually figure out if the invoke was "valid" initially, IMHO the real issue is that we return a messages saying "successfully invoked transaction" when in reality all that has really happened is that we have successfully submitted the transaction.  Subtle difference, yes, but still more accurate

**Comment by angrbrd** [comment]
@mastersingh24, I totally agree too. I vote that we return "successfully submitted transaction" (or some such). The act of waiting for the transaction to execute and notify is a good candidate for the SDK but I think that would be better addressed as a separate issue.
