### ISSUE TITLE
Discussion: Detecting Non-determinism

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#841]
In a discussion with @kchristidis and @corecode last week, some of the limitations and design points of Sieve were brought up.

Although the 'correctness' of Sieve as defined is not in question, I was hoping to discuss and get thoughts from @vukolic or others on the subject of detecting non-determinism.

The concerns all stem from accepting the idea that f+1 of the same result is good enough to treat a transaction as deterministic (even though it may not be).  The counter-point would be that perhaps we do not care if a transaction is non-deterministic, so long as we are getting a result that at least one honest node agrees on, but this seems to have some drawbacks.  Although each of the below is essentially a rehashing of this concern, they are presented separately because of their separate implications.

---

**Sycophantic Byzantine**

Suppose a chaincode is deployed which is roughly `return rand.Int()`.  For all non-byzantine replicas, this chaincode will practically never return the same result.  Assume the byzantine replicas eagerly listen for the very first result, and immediately reply with their own `Verify` that matches this first result.  There will be f+1 matching verify messages, so the invocation will be inferred to be deterministic, and the remaining 2f replicas will need to perform state sync to the f+1.  Because f of the f+1 replicas are byzantine, they can each timeout, send malicious data, etc. and force the remaining 2f replicas to search for the single non-byzantine replica which has the data they need.  This seems like an attack which could drastically decrease throughput of the network.  But this bad  transaction has no hope of ever being classified as non-deterministic, because the byzantine replicas will always ensure there are f+1 same replies, so there is no hope to 'quarantine' it.

---

**Ignored Non-determinism**

Suppose a Sieve network with f=1 is deployed, and a transaction is executed and replicas 1,2,3, and 4 produce results a,a,b, and b respectively.  Discarding any one of the results as potentially malicious and byzantine, two non-byzantine replicas then must have arrived at two different results.  This transaction is therefore unquestionably non-deterministic.  However, it will be judged to be deterministic and committed.

---

**Ignored Majority**

Suppose a Sieve network is deployed, a transaction is executed and f+1 replicas report a result of A, while 2f replicas report a result of B.  Even though B has vastly more 'votes' (asymptotically double the votes of A, as f increases), it is still possible that result A is committed.

---

**A Proposal**

What if the the threshold for determinism was set to be 2f+1 same results?  

The most obvious problem with this approach is that a non-deterministic transaction among 2f+1 honest nodes, and f silent byzantine nodes could not be decided, but a view-change-like timer could be introduced.  Non-byzantine replicas can be expected to reply to a request 'within a reasonable time', so if a request is deterministic, the primary should record 2f+1 same results within the timer window.  If the primary does not, then it can be assumed that either the transaction is non-deterministic, or it is performing too slowly to wait for.  Both of which seem like valid reasons to quarantine a chaincode for human review.

Non-determinism could be concluded as soon as the primary obtained f+1 assertions that f+1 results are wrong (ie, at least one correct replica disagrees with at least one other correct replica). For instance, f+2 different results, would be sufficient to show f+1 replicas disagree with each of the f+2 results.  Similarly, f+1 of result A, and f+1 of result B would be sufficient to conclude non-determinism.

In the common case, of deterministic transactions, the throughput should be the same as standard PBFT.  In the uncommon case, of non-deterministic transactions, the byzantine nodes could force the non-deterministic timer to pop each time before progress could be made.  The advantage is that the transaction could then be quarantined, and the byzantine nodes could not constantly force the slowdown of the system unlike the Sycophantic Byzantine scenario.  Of course, if the byzantine nodes can constantly introduce new non-determinstic chaincodes into the system, the slowness problem re-emerges, but at least the non-determinism would be flagged, and an audit to its origin could be performed.

**Comment by corecode** [comment]
I like your proposal.

**Comment by vukolic** [comment]
The proposal for waiting 2f+1 same results to declare det tx (otherwise non-det) is not good.

It would allow, as soon as there is a partition of a single correct replica, a byzantine replica to quarantine a perfectly deterministic transaction. Example: 2f replies from correct replicas are the same, 1 from Byz is different and the timeout fires. You just quarantined a deterministic transaction. So we would be ending up with a "BFT" system that never works with asynchrony AND Byzantine faults. 

Notice that one can assume that _simultaneous_ partitions among correct replicas AND Byzantine faults are rare, but this is a different model known (since recently) as the XFT model: http://arxiv.org/abs/1502.05831 We may/will develop OBC consensus with XFT model in mind - but this is not BFT - and we are doing vanilla BFT now.

Just a side note: waiting for 2f+1, or 10f+1 same replies for that matter, does not guarantee that the tx is deterministic. There is always a probability I roll the dice 2f+1 or 10f+1 times and get 6 all the time... 

Re the other part of the proposal about declaring non-determinism as soon as you have the proof of f+2 different values, or 2 sets of f+1 votes for different values - this is ok. But notice that this can only be an _optimization_ in Sieve: there will always be a corner case in which you will get f+1 same replies and f different ones - and you cannot wait for more answers. In this case tx needs to be declared deterministic.

**Comment by corecode** [comment]
Oh, I think I missed this point in jyellick's proposal.  I thought that we would wait for 2f+1 same replies up to some timeout (fairly short one, see below), and then decide based on the result.  If there are f+2 pairwise different results, we know the transaction is nondeterministic (we can stop the timeout at that point anyways).  Otherwise, we accept the transaction as deterministic enough.

Timeout:  this timeout should be sized so that the overall latency will be lower than prematurely accepting a non-deterministic request, and having to perform state transfer.

**Comment by kchristidis** [comment]
Jason's "within a reasonable time" statement implies a timer -- and this was also the case when he made that proposal last week IIRC.

What's being proposed here, I think, is a different trade-off than the one that Sieve currently uses. So, RE: quarantining a deterministic transaction. Yes, this will happen if we haven't collected 2f+1 within a certain timeframe. But we introduce some synchrony to the network for the benefit of better (but not perfect -- yes) ND filtering.

(FWIW, I like that trade-off.)

**Comment by vukolic** [comment]
@corecode - this, as an optimization, is fine
@kchristidis - as discussed above, this is not fine in the eventually synchronous BFT model we assume. It goes towards the XFT model - and we will come there, just not yet.

**Comment by jyellick** [comment]
@vukolic I think the partitioned vs faulty claims are maybe a little conflated in my head.

It seems that a partitioned non-byzantine replica, and a byzantine replica should both count against the 'at most f faulty replicas' condition promised to PBFT.  I agree if there are f byzantine replicas, and 1 partitioned non-byzantine replica, then a deterministic transaction could be flagged as non-deterministic, as a timer would expire with only 2f identical results.  However, this seems like f+1 faulty replicas to me?

If there is a mixture of byzantine and partitioned non-byzantine replicas, I don't see the problem, so long as the total number is less than or equal to f.  There will still be the 2f+1 valid replies from non-faulty replicas necessary to have the transaction qualify as deterministic. (I use the phrase 'qualify as deterministic' loosely here, as you correctly point out, it is impossible to ever determine a transaction is deterministic based only on its output.  Perhaps a more correct phrase would be 'qualify as not necessarily non-deterministic').

If the biggest concern is with improperly quarantining transactions, one possible solution could be that the transaction be 'tentatively quarantined'.  In this state, when a previously partitioned replica returns to the network, it could vote on the result to bring the result up to 2f+1 same results and 'un-quarantine' the transaction.  This would introduce some concerns about unbounded growth, but I think could be addressed once properly thought through.

**Comment by vukolic** [comment]
@jyellick The model you are describing, in which both Byzantine replicas and partitioned replicas count towards the threshold f - is exactly the XFT model that [1] describes. Please have a look at that one. 

What you continue to describe is a sound protocol in the XFT model. There is one caveat though, In XFT one can devise protocols that rely on 2f+1 replicas and not 3f+1, so you would be essentially spending f additional replicas. 

I am planing with @corecode to start (soon) implementing an XFT protocol (perhaps XPaxos as described in the paper - or a variant of it) in OBC. If you want to join that effort - that would be awesome. 

[1] Shengyun Liu, Paolo Viotti, Christian Cachin, Vivien Quéma, Marko Vukolić. XFT: Practical Fault Tolerance Beyond Crashes. http://arxiv.org/abs/1502.05831

**Comment by jyellick** [comment]
@vukolic Thanks for the paper link.  I'll take a look.  Would definitely be interested in helping out with the XFT effort, just let me know.
