### ISSUE TITLE
Bouncing a vp in Batch Consensus with security and privacy on results in unclear error message

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#868]
Description:

Bouncing a member of consensus peers with security and privacy turned on leads to an unclear message

Steps to repro:
1.  Setup 4 VPs and a CA in Consensus Batch config with security and privacy on
2.  Take down the 4th peer (vp3)
3.  View logs on other peers who now cannot communicate with 4th peer
4.  Start peer back up, giving the secret in the obcca.yaml for that server.
5.  The logs show a series of errors (attached) that revolve around a bad token or secret

Results:

![0bounce](https://cloud.githubusercontent.com/assets/17052305/13992613/2512dab8-f0f3-11e5-9cdb-820b186b4777.JPG)

Expected Results:  Per SandboxSetup.md, you can only login with a user/secret pair once, so this is expected behavior but a confusing message.  Expect a message that tells the user this login has been used and cannot be used again.

**Comment by tuand27613** [comment]
I'm asking @adecaro to take a look first since he's my main contact for cryto :)  . Feel free to reassign as needed.

There are other test cases where stopping a re-starting a validating peer work.  It seems this happens only when both security and privacy are enabled.

**Comment by adecaro** [comment]
@RicHernandez2, may you tell me more about Step 2 "Take down the 4th peer (vp3)".
Does it mean that you clean up also the state of the peer stored on the disk. 

The point is that the pair (enrollID, enrollPWD) is a one time pair. If you take down a peer and remove its state stored on the disk then the pair will not work anymore. If you don't remove the state then the peer can restart from where he left because he doesn't need to register again.

For what I see from the logs, it seems that the peer is trying to register again itself to the CA using the same enrollment pair.

**Comment by adecaro** [comment]
@RicHernandez2, may we close this?

**Comment by binhn** [comment]
Suggest to close per @adecaro

**Comment by RicHernandez2** [comment]
Closed

**Comment by bmos299** [comment]
@RicHernandez2, It this token is already in use, and still usable, shouldn't the message reflect that?  This isn't a token rematch, but trying to use an existing token.
